// Copyright (c) 2025 Jimmy O'Rourke
// Licensed under and subject to the terms of the LICENSE file accompanying this distribution.
// Official repository: https://github.com/jimmyorourke/plotlypp

// Autogenerated by plotlypp/generator, from official Plotly sources.
// See https://plotly.com/graphing-libraries.
// Do not edit, changes may be overwritten!

#pragma once

namespace plotlypp {

std::string Scatter3D::to_string(Surfaceaxis e) {
    switch(e) {
        case Surfaceaxis::_1: return "-1";
        case Surfaceaxis::NUM_0: return "0";
        case Surfaceaxis::NUM_1: return "1";
        case Surfaceaxis::NUM_2: return "2";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::to_string(Textposition e) {
    switch(e) {
        case Textposition::TOP_LEFT: return "top left";
        case Textposition::TOP_CENTER: return "top center";
        case Textposition::TOP_RIGHT: return "top right";
        case Textposition::MIDDLE_LEFT: return "middle left";
        case Textposition::MIDDLE_CENTER: return "middle center";
        case Textposition::MIDDLE_RIGHT: return "middle right";
        case Textposition::BOTTOM_LEFT: return "bottom left";
        case Textposition::BOTTOM_CENTER: return "bottom center";
        case Textposition::BOTTOM_RIGHT: return "bottom right";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::to_string(Visible e) {
    switch(e) {
        case Visible::TRUE: return "True";
        case Visible::FALSE: return "False";
        case Visible::LEGENDONLY: return "legendonly";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::to_string(Xcalendar e) {
    switch(e) {
        case Xcalendar::CHINESE: return "chinese";
        case Xcalendar::COPTIC: return "coptic";
        case Xcalendar::DISCWORLD: return "discworld";
        case Xcalendar::ETHIOPIAN: return "ethiopian";
        case Xcalendar::GREGORIAN: return "gregorian";
        case Xcalendar::HEBREW: return "hebrew";
        case Xcalendar::ISLAMIC: return "islamic";
        case Xcalendar::JALALI: return "jalali";
        case Xcalendar::JULIAN: return "julian";
        case Xcalendar::MAYAN: return "mayan";
        case Xcalendar::NANAKSHAHI: return "nanakshahi";
        case Xcalendar::NEPALI: return "nepali";
        case Xcalendar::PERSIAN: return "persian";
        case Xcalendar::TAIWAN: return "taiwan";
        case Xcalendar::THAI: return "thai";
        case Xcalendar::UMMALQURA: return "ummalqura";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::to_string(Ycalendar e) {
    switch(e) {
        case Ycalendar::CHINESE: return "chinese";
        case Ycalendar::COPTIC: return "coptic";
        case Ycalendar::DISCWORLD: return "discworld";
        case Ycalendar::ETHIOPIAN: return "ethiopian";
        case Ycalendar::GREGORIAN: return "gregorian";
        case Ycalendar::HEBREW: return "hebrew";
        case Ycalendar::ISLAMIC: return "islamic";
        case Ycalendar::JALALI: return "jalali";
        case Ycalendar::JULIAN: return "julian";
        case Ycalendar::MAYAN: return "mayan";
        case Ycalendar::NANAKSHAHI: return "nanakshahi";
        case Ycalendar::NEPALI: return "nepali";
        case Ycalendar::PERSIAN: return "persian";
        case Ycalendar::TAIWAN: return "taiwan";
        case Ycalendar::THAI: return "thai";
        case Ycalendar::UMMALQURA: return "ummalqura";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::to_string(Zcalendar e) {
    switch(e) {
        case Zcalendar::CHINESE: return "chinese";
        case Zcalendar::COPTIC: return "coptic";
        case Zcalendar::DISCWORLD: return "discworld";
        case Zcalendar::ETHIOPIAN: return "ethiopian";
        case Zcalendar::GREGORIAN: return "gregorian";
        case Zcalendar::HEBREW: return "hebrew";
        case Zcalendar::ISLAMIC: return "islamic";
        case Zcalendar::JALALI: return "jalali";
        case Zcalendar::JULIAN: return "julian";
        case Zcalendar::MAYAN: return "mayan";
        case Zcalendar::NANAKSHAHI: return "nanakshahi";
        case Zcalendar::NEPALI: return "nepali";
        case Zcalendar::PERSIAN: return "persian";
        case Zcalendar::TAIWAN: return "taiwan";
        case Zcalendar::THAI: return "thai";
        case Zcalendar::UMMALQURA: return "ummalqura";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scatter3D& Scatter3D::connectgaps(bool f) {
    json["connectgaps"] = std::move(f);
    return *this;
}

template <typename T, typename>
Scatter3D& Scatter3D::customdata(std::vector<T> f) {
    json["customdata"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::customdatasrc(std::string f) {
    json["customdatasrc"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::error_x(Error_X f) {
    json["error_x"] = std::move(f.json);
    return *this;
}

Scatter3D& Scatter3D::error_y(Error_Y f) {
    json["error_y"] = std::move(f.json);
    return *this;
}

Scatter3D& Scatter3D::error_z(Error_Z f) {
    json["error_z"] = std::move(f.json);
    return *this;
}

Scatter3D& Scatter3D::hoverinfo(std::string f) {
    json["hoverinfo"] = std::move(f);
    return *this;
}
Scatter3D& Scatter3D::hoverinfo(std::vector<std::string> f) {
    json["hoverinfo"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::hoverinfosrc(std::string f) {
    json["hoverinfosrc"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::hoverlabel(Hoverlabel f) {
    json["hoverlabel"] = std::move(f.json);
    return *this;
}

Scatter3D& Scatter3D::hovertemplate(std::string f) {
    json["hovertemplate"] = std::move(f);
    return *this;
}
Scatter3D& Scatter3D::hovertemplate(std::vector<std::string> f) {
    json["hovertemplate"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::hovertemplatesrc(std::string f) {
    json["hovertemplatesrc"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::hovertext(std::string f) {
    json["hovertext"] = std::move(f);
    return *this;
}
Scatter3D& Scatter3D::hovertext(std::vector<std::string> f) {
    json["hovertext"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::hovertextsrc(std::string f) {
    json["hovertextsrc"] = std::move(f);
    return *this;
}

template <typename T, typename>
Scatter3D& Scatter3D::ids(std::vector<T> f) {
    json["ids"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::idssrc(std::string f) {
    json["idssrc"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::legend(std::string f) {
    json["legend"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::legendgroup(std::string f) {
    json["legendgroup"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::legendgrouptitle(Legendgrouptitle f) {
    json["legendgrouptitle"] = std::move(f.json);
    return *this;
}

Scatter3D& Scatter3D::legendrank(double f) {
    json["legendrank"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::legendwidth(double f) {
    json["legendwidth"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::line(Line f) {
    json["line"] = std::move(f.json);
    return *this;
}

Scatter3D& Scatter3D::marker(Marker f) {
    json["marker"] = std::move(f.json);
    return *this;
}

template <typename T>
Scatter3D& Scatter3D::meta(T f) {
    json["meta"] = std::move(f);
    return *this;
}
template <typename T>
Scatter3D& Scatter3D::meta(std::vector<T> f) {
    json["meta"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::metasrc(std::string f) {
    json["metasrc"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::mode(std::string f) {
    json["mode"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::projection(Projection f) {
    json["projection"] = std::move(f.json);
    return *this;
}

Scatter3D& Scatter3D::scene(std::string f) {
    json["scene"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::showlegend(bool f) {
    json["showlegend"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::stream(Stream f) {
    json["stream"] = std::move(f.json);
    return *this;
}

Scatter3D& Scatter3D::surfaceaxis(enum Surfaceaxis f) {
    json["surfaceaxis"] = to_string(f);
    return *this;
}

Scatter3D& Scatter3D::surfacecolor(std::string f) {
    json["surfacecolor"] = std::move(f);
    return *this;
}
Scatter3D& Scatter3D::surfacecolor(double f) {
    json["surfacecolor"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}
Scatter3D& Scatter3D::text(std::vector<std::string> f) {
    json["text"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::textfont(Textfont f) {
    json["textfont"] = std::move(f.json);
    return *this;
}

Scatter3D& Scatter3D::textposition(enum Textposition f) {
    json["textposition"] = to_string(f);
    return *this;
}
Scatter3D& Scatter3D::textposition(const std::vector<enum Textposition>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["textposition"] = std::move(stringified);
    return *this;
}

Scatter3D& Scatter3D::textpositionsrc(std::string f) {
    json["textpositionsrc"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::textsrc(std::string f) {
    json["textsrc"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::texttemplate(std::string f) {
    json["texttemplate"] = std::move(f);
    return *this;
}
Scatter3D& Scatter3D::texttemplate(std::vector<std::string> f) {
    json["texttemplate"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::texttemplatesrc(std::string f) {
    json["texttemplatesrc"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::uid(std::string f) {
    json["uid"] = std::move(f);
    return *this;
}

template <typename T>
Scatter3D& Scatter3D::uirevision(T f) {
    json["uirevision"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::visible(enum Visible f) {
    json["visible"] = to_string(f);
    return *this;
}

template <typename T, typename>
Scatter3D& Scatter3D::x(std::vector<T> f) {
    json["x"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::xcalendar(enum Xcalendar f) {
    json["xcalendar"] = to_string(f);
    return *this;
}

Scatter3D& Scatter3D::xhoverformat(std::string f) {
    json["xhoverformat"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::xsrc(std::string f) {
    json["xsrc"] = std::move(f);
    return *this;
}

template <typename T, typename>
Scatter3D& Scatter3D::y(std::vector<T> f) {
    json["y"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::ycalendar(enum Ycalendar f) {
    json["ycalendar"] = to_string(f);
    return *this;
}

Scatter3D& Scatter3D::yhoverformat(std::string f) {
    json["yhoverformat"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::ysrc(std::string f) {
    json["ysrc"] = std::move(f);
    return *this;
}

template <typename T, typename>
Scatter3D& Scatter3D::z(std::vector<T> f) {
    json["z"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::zcalendar(enum Zcalendar f) {
    json["zcalendar"] = to_string(f);
    return *this;
}

Scatter3D& Scatter3D::zhoverformat(std::string f) {
    json["zhoverformat"] = std::move(f);
    return *this;
}

Scatter3D& Scatter3D::zsrc(std::string f) {
    json["zsrc"] = std::move(f);
    return *this;
}

std::string Scatter3D::Error_X::to_string(Type e) {
    switch(e) {
        case Type::PERCENT: return "percent";
        case Type::CONSTANT: return "constant";
        case Type::SQRT: return "sqrt";
        case Type::DATA: return "data";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

template <typename T, typename>
Scatter3D::Error_X& Scatter3D::Error_X::array(std::vector<T> f) {
    json["array"] = std::move(f);
    return *this;
}

template <typename T, typename>
Scatter3D::Error_X& Scatter3D::Error_X::arrayminus(std::vector<T> f) {
    json["arrayminus"] = std::move(f);
    return *this;
}

Scatter3D::Error_X& Scatter3D::Error_X::arrayminussrc(std::string f) {
    json["arrayminussrc"] = std::move(f);
    return *this;
}

Scatter3D::Error_X& Scatter3D::Error_X::arraysrc(std::string f) {
    json["arraysrc"] = std::move(f);
    return *this;
}

Scatter3D::Error_X& Scatter3D::Error_X::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Error_X& Scatter3D::Error_X::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

Scatter3D::Error_X& Scatter3D::Error_X::copy_zstyle(bool f) {
    json["copy_zstyle"] = std::move(f);
    return *this;
}

Scatter3D::Error_X& Scatter3D::Error_X::symmetric(bool f) {
    json["symmetric"] = std::move(f);
    return *this;
}

Scatter3D::Error_X& Scatter3D::Error_X::thickness(double f) {
    json["thickness"] = std::move(f);
    return *this;
}

Scatter3D::Error_X& Scatter3D::Error_X::traceref(int f) {
    json["traceref"] = std::move(f);
    return *this;
}

Scatter3D::Error_X& Scatter3D::Error_X::tracerefminus(int f) {
    json["tracerefminus"] = std::move(f);
    return *this;
}

Scatter3D::Error_X& Scatter3D::Error_X::type(enum Type f) {
    json["type"] = to_string(f);
    return *this;
}

Scatter3D::Error_X& Scatter3D::Error_X::value(double f) {
    json["value"] = std::move(f);
    return *this;
}

Scatter3D::Error_X& Scatter3D::Error_X::valueminus(double f) {
    json["valueminus"] = std::move(f);
    return *this;
}

Scatter3D::Error_X& Scatter3D::Error_X::visible(bool f) {
    json["visible"] = std::move(f);
    return *this;
}

Scatter3D::Error_X& Scatter3D::Error_X::width(double f) {
    json["width"] = std::move(f);
    return *this;
}

std::string Scatter3D::Error_Y::to_string(Type e) {
    switch(e) {
        case Type::PERCENT: return "percent";
        case Type::CONSTANT: return "constant";
        case Type::SQRT: return "sqrt";
        case Type::DATA: return "data";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

template <typename T, typename>
Scatter3D::Error_Y& Scatter3D::Error_Y::array(std::vector<T> f) {
    json["array"] = std::move(f);
    return *this;
}

template <typename T, typename>
Scatter3D::Error_Y& Scatter3D::Error_Y::arrayminus(std::vector<T> f) {
    json["arrayminus"] = std::move(f);
    return *this;
}

Scatter3D::Error_Y& Scatter3D::Error_Y::arrayminussrc(std::string f) {
    json["arrayminussrc"] = std::move(f);
    return *this;
}

Scatter3D::Error_Y& Scatter3D::Error_Y::arraysrc(std::string f) {
    json["arraysrc"] = std::move(f);
    return *this;
}

Scatter3D::Error_Y& Scatter3D::Error_Y::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Error_Y& Scatter3D::Error_Y::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

Scatter3D::Error_Y& Scatter3D::Error_Y::copy_zstyle(bool f) {
    json["copy_zstyle"] = std::move(f);
    return *this;
}

Scatter3D::Error_Y& Scatter3D::Error_Y::symmetric(bool f) {
    json["symmetric"] = std::move(f);
    return *this;
}

Scatter3D::Error_Y& Scatter3D::Error_Y::thickness(double f) {
    json["thickness"] = std::move(f);
    return *this;
}

Scatter3D::Error_Y& Scatter3D::Error_Y::traceref(int f) {
    json["traceref"] = std::move(f);
    return *this;
}

Scatter3D::Error_Y& Scatter3D::Error_Y::tracerefminus(int f) {
    json["tracerefminus"] = std::move(f);
    return *this;
}

Scatter3D::Error_Y& Scatter3D::Error_Y::type(enum Type f) {
    json["type"] = to_string(f);
    return *this;
}

Scatter3D::Error_Y& Scatter3D::Error_Y::value(double f) {
    json["value"] = std::move(f);
    return *this;
}

Scatter3D::Error_Y& Scatter3D::Error_Y::valueminus(double f) {
    json["valueminus"] = std::move(f);
    return *this;
}

Scatter3D::Error_Y& Scatter3D::Error_Y::visible(bool f) {
    json["visible"] = std::move(f);
    return *this;
}

Scatter3D::Error_Y& Scatter3D::Error_Y::width(double f) {
    json["width"] = std::move(f);
    return *this;
}

std::string Scatter3D::Error_Z::to_string(Type e) {
    switch(e) {
        case Type::PERCENT: return "percent";
        case Type::CONSTANT: return "constant";
        case Type::SQRT: return "sqrt";
        case Type::DATA: return "data";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

template <typename T, typename>
Scatter3D::Error_Z& Scatter3D::Error_Z::array(std::vector<T> f) {
    json["array"] = std::move(f);
    return *this;
}

template <typename T, typename>
Scatter3D::Error_Z& Scatter3D::Error_Z::arrayminus(std::vector<T> f) {
    json["arrayminus"] = std::move(f);
    return *this;
}

Scatter3D::Error_Z& Scatter3D::Error_Z::arrayminussrc(std::string f) {
    json["arrayminussrc"] = std::move(f);
    return *this;
}

Scatter3D::Error_Z& Scatter3D::Error_Z::arraysrc(std::string f) {
    json["arraysrc"] = std::move(f);
    return *this;
}

Scatter3D::Error_Z& Scatter3D::Error_Z::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Error_Z& Scatter3D::Error_Z::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

Scatter3D::Error_Z& Scatter3D::Error_Z::symmetric(bool f) {
    json["symmetric"] = std::move(f);
    return *this;
}

Scatter3D::Error_Z& Scatter3D::Error_Z::thickness(double f) {
    json["thickness"] = std::move(f);
    return *this;
}

Scatter3D::Error_Z& Scatter3D::Error_Z::traceref(int f) {
    json["traceref"] = std::move(f);
    return *this;
}

Scatter3D::Error_Z& Scatter3D::Error_Z::tracerefminus(int f) {
    json["tracerefminus"] = std::move(f);
    return *this;
}

Scatter3D::Error_Z& Scatter3D::Error_Z::type(enum Type f) {
    json["type"] = to_string(f);
    return *this;
}

Scatter3D::Error_Z& Scatter3D::Error_Z::value(double f) {
    json["value"] = std::move(f);
    return *this;
}

Scatter3D::Error_Z& Scatter3D::Error_Z::valueminus(double f) {
    json["valueminus"] = std::move(f);
    return *this;
}

Scatter3D::Error_Z& Scatter3D::Error_Z::visible(bool f) {
    json["visible"] = std::move(f);
    return *this;
}

Scatter3D::Error_Z& Scatter3D::Error_Z::width(double f) {
    json["width"] = std::move(f);
    return *this;
}

std::string Scatter3D::Hoverlabel::to_string(Align e) {
    switch(e) {
        case Align::LEFT: return "left";
        case Align::RIGHT: return "right";
        case Align::AUTO: return "auto";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scatter3D::Hoverlabel& Scatter3D::Hoverlabel::align(enum Align f) {
    json["align"] = to_string(f);
    return *this;
}
Scatter3D::Hoverlabel& Scatter3D::Hoverlabel::align(const std::vector<enum Align>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["align"] = std::move(stringified);
    return *this;
}

Scatter3D::Hoverlabel& Scatter3D::Hoverlabel::alignsrc(std::string f) {
    json["alignsrc"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel& Scatter3D::Hoverlabel::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
Scatter3D::Hoverlabel& Scatter3D::Hoverlabel::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
Scatter3D::Hoverlabel& Scatter3D::Hoverlabel::bgcolor(std::vector<std::string> f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
Scatter3D::Hoverlabel& Scatter3D::Hoverlabel::bgcolor(std::vector<double> f) {
    json["bgcolor"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel& Scatter3D::Hoverlabel::bgcolorsrc(std::string f) {
    json["bgcolorsrc"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel& Scatter3D::Hoverlabel::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
Scatter3D::Hoverlabel& Scatter3D::Hoverlabel::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
Scatter3D::Hoverlabel& Scatter3D::Hoverlabel::bordercolor(std::vector<std::string> f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
Scatter3D::Hoverlabel& Scatter3D::Hoverlabel::bordercolor(std::vector<double> f) {
    json["bordercolor"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel& Scatter3D::Hoverlabel::bordercolorsrc(std::string f) {
    json["bordercolorsrc"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel& Scatter3D::Hoverlabel::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}

Scatter3D::Hoverlabel& Scatter3D::Hoverlabel::namelength(int f) {
    json["namelength"] = std::move(f);
    return *this;
}
Scatter3D::Hoverlabel& Scatter3D::Hoverlabel::namelength(std::vector<int> f) {
    json["namelength"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel& Scatter3D::Hoverlabel::namelengthsrc(std::string f) {
    json["namelengthsrc"] = std::move(f);
    return *this;
}

std::string Scatter3D::Hoverlabel::Font::to_string(Style e) {
    switch(e) {
        case Style::NORMAL: return "normal";
        case Style::ITALIC: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Hoverlabel::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::NORMAL: return "normal";
        case Textcase::WORD_CAPS: return "word caps";
        case Textcase::UPPER: return "upper";
        case Textcase::LOWER: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Hoverlabel::Font::to_string(Variant e) {
    switch(e) {
        case Variant::NORMAL: return "normal";
        case Variant::SMALL_CAPS: return "small-caps";
        case Variant::ALL_SMALL_CAPS: return "all-small-caps";
        case Variant::ALL_PETITE_CAPS: return "all-petite-caps";
        case Variant::PETITE_CAPS: return "petite-caps";
        case Variant::UNICASE: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::color(std::vector<std::string> f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::color(std::vector<double> f) {
    json["color"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::family(std::vector<std::string> f) {
    json["family"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}
Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::lineposition(std::vector<std::string> f) {
    json["lineposition"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::linepositionsrc(std::string f) {
    json["linepositionsrc"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}
Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::shadow(std::vector<std::string> f) {
    json["shadow"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::shadowsrc(std::string f) {
    json["shadowsrc"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::size(std::vector<double> f) {
    json["size"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}
Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::style(const std::vector<enum Style>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["style"] = std::move(stringified);
    return *this;
}

Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}
Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::textcase(const std::vector<enum Textcase>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["textcase"] = std::move(stringified);
    return *this;
}

Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::textcasesrc(std::string f) {
    json["textcasesrc"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}
Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::variant(const std::vector<enum Variant>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["variant"] = std::move(stringified);
    return *this;
}

Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::weight(std::vector<int> f) {
    json["weight"] = std::move(f);
    return *this;
}

Scatter3D::Hoverlabel::Font& Scatter3D::Hoverlabel::Font::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}


Scatter3D::Legendgrouptitle& Scatter3D::Legendgrouptitle::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}

Scatter3D::Legendgrouptitle& Scatter3D::Legendgrouptitle::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

std::string Scatter3D::Legendgrouptitle::Font::to_string(Style e) {
    switch(e) {
        case Style::NORMAL: return "normal";
        case Style::ITALIC: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Legendgrouptitle::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::NORMAL: return "normal";
        case Textcase::WORD_CAPS: return "word caps";
        case Textcase::UPPER: return "upper";
        case Textcase::LOWER: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Legendgrouptitle::Font::to_string(Variant e) {
    switch(e) {
        case Variant::NORMAL: return "normal";
        case Variant::SMALL_CAPS: return "small-caps";
        case Variant::ALL_SMALL_CAPS: return "all-small-caps";
        case Variant::ALL_PETITE_CAPS: return "all-petite-caps";
        case Variant::PETITE_CAPS: return "petite-caps";
        case Variant::UNICASE: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scatter3D::Legendgrouptitle::Font& Scatter3D::Legendgrouptitle::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Legendgrouptitle::Font& Scatter3D::Legendgrouptitle::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

Scatter3D::Legendgrouptitle::Font& Scatter3D::Legendgrouptitle::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

Scatter3D::Legendgrouptitle::Font& Scatter3D::Legendgrouptitle::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

Scatter3D::Legendgrouptitle::Font& Scatter3D::Legendgrouptitle::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

Scatter3D::Legendgrouptitle::Font& Scatter3D::Legendgrouptitle::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

Scatter3D::Legendgrouptitle::Font& Scatter3D::Legendgrouptitle::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

Scatter3D::Legendgrouptitle::Font& Scatter3D::Legendgrouptitle::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

Scatter3D::Legendgrouptitle::Font& Scatter3D::Legendgrouptitle::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

Scatter3D::Legendgrouptitle::Font& Scatter3D::Legendgrouptitle::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}

std::string Scatter3D::Line::to_string(Dash e) {
    switch(e) {
        case Dash::DASH: return "dash";
        case Dash::DASHDOT: return "dashdot";
        case Dash::DOT: return "dot";
        case Dash::LONGDASH: return "longdash";
        case Dash::LONGDASHDOT: return "longdashdot";
        case Dash::SOLID: return "solid";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scatter3D::Line& Scatter3D::Line::autocolorscale(bool f) {
    json["autocolorscale"] = std::move(f);
    return *this;
}

Scatter3D::Line& Scatter3D::Line::cauto(bool f) {
    json["cauto"] = std::move(f);
    return *this;
}

Scatter3D::Line& Scatter3D::Line::cmax(double f) {
    json["cmax"] = std::move(f);
    return *this;
}

Scatter3D::Line& Scatter3D::Line::cmid(double f) {
    json["cmid"] = std::move(f);
    return *this;
}

Scatter3D::Line& Scatter3D::Line::cmin(double f) {
    json["cmin"] = std::move(f);
    return *this;
}

Scatter3D::Line& Scatter3D::Line::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Line& Scatter3D::Line::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Line& Scatter3D::Line::color(std::vector<std::string> f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Line& Scatter3D::Line::color(std::vector<double> f) {
    json["color"] = std::move(f);
    return *this;
}

Scatter3D::Line& Scatter3D::Line::coloraxis(std::string f) {
    json["coloraxis"] = std::move(f);
    return *this;
}

Scatter3D::Line& Scatter3D::Line::colorbar(Colorbar f) {
    json["colorbar"] = std::move(f.json);
    return *this;
}

Scatter3D::Line& Scatter3D::Line::colorscale(std::string f) {
    json["colorscale"] = std::move(f);
    return *this;
}
Scatter3D::Line& Scatter3D::Line::colorscale(std::vector<std::pair<double, std::string>> f) {
    json["colorscale"] = std::move(f);
    return *this;
}

Scatter3D::Line& Scatter3D::Line::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

Scatter3D::Line& Scatter3D::Line::dash(enum Dash f) {
    json["dash"] = to_string(f);
    return *this;
}

Scatter3D::Line& Scatter3D::Line::reversescale(bool f) {
    json["reversescale"] = std::move(f);
    return *this;
}

Scatter3D::Line& Scatter3D::Line::showscale(bool f) {
    json["showscale"] = std::move(f);
    return *this;
}

Scatter3D::Line& Scatter3D::Line::width(double f) {
    json["width"] = std::move(f);
    return *this;
}

std::string Scatter3D::Line::Colorbar::to_string(Exponentformat e) {
    switch(e) {
        case Exponentformat::NONE: return "none";
        case Exponentformat::E: return "E";
        case Exponentformat::POWER: return "power";
        case Exponentformat::SI: return "SI";
        case Exponentformat::B: return "B";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Line::Colorbar::to_string(Lenmode e) {
    switch(e) {
        case Lenmode::FRACTION: return "fraction";
        case Lenmode::PIXELS: return "pixels";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Line::Colorbar::to_string(Orientation e) {
    switch(e) {
        case Orientation::H: return "h";
        case Orientation::V: return "v";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Line::Colorbar::to_string(Showexponent e) {
    switch(e) {
        case Showexponent::ALL: return "all";
        case Showexponent::FIRST: return "first";
        case Showexponent::LAST: return "last";
        case Showexponent::NONE: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Line::Colorbar::to_string(Showtickprefix e) {
    switch(e) {
        case Showtickprefix::ALL: return "all";
        case Showtickprefix::FIRST: return "first";
        case Showtickprefix::LAST: return "last";
        case Showtickprefix::NONE: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Line::Colorbar::to_string(Showticksuffix e) {
    switch(e) {
        case Showticksuffix::ALL: return "all";
        case Showticksuffix::FIRST: return "first";
        case Showticksuffix::LAST: return "last";
        case Showticksuffix::NONE: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Line::Colorbar::to_string(Thicknessmode e) {
    switch(e) {
        case Thicknessmode::FRACTION: return "fraction";
        case Thicknessmode::PIXELS: return "pixels";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Line::Colorbar::to_string(Ticklabeloverflow e) {
    switch(e) {
        case Ticklabeloverflow::ALLOW: return "allow";
        case Ticklabeloverflow::HIDE_PAST_DIV: return "hide past div";
        case Ticklabeloverflow::HIDE_PAST_DOMAIN: return "hide past domain";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Line::Colorbar::to_string(Ticklabelposition e) {
    switch(e) {
        case Ticklabelposition::OUTSIDE: return "outside";
        case Ticklabelposition::INSIDE: return "inside";
        case Ticklabelposition::OUTSIDE_TOP: return "outside top";
        case Ticklabelposition::INSIDE_TOP: return "inside top";
        case Ticklabelposition::OUTSIDE_LEFT: return "outside left";
        case Ticklabelposition::INSIDE_LEFT: return "inside left";
        case Ticklabelposition::OUTSIDE_RIGHT: return "outside right";
        case Ticklabelposition::INSIDE_RIGHT: return "inside right";
        case Ticklabelposition::OUTSIDE_BOTTOM: return "outside bottom";
        case Ticklabelposition::INSIDE_BOTTOM: return "inside bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Line::Colorbar::to_string(Tickmode e) {
    switch(e) {
        case Tickmode::AUTO: return "auto";
        case Tickmode::LINEAR: return "linear";
        case Tickmode::ARRAY: return "array";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Line::Colorbar::to_string(Ticks e) {
    switch(e) {
        case Ticks::OUTSIDE: return "outside";
        case Ticks::INSIDE: return "inside";
        case Ticks::EMPTY: return "";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Line::Colorbar::to_string(Xanchor e) {
    switch(e) {
        case Xanchor::LEFT: return "left";
        case Xanchor::CENTER: return "center";
        case Xanchor::RIGHT: return "right";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Line::Colorbar::to_string(Xref e) {
    switch(e) {
        case Xref::CONTAINER: return "container";
        case Xref::PAPER: return "paper";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Line::Colorbar::to_string(Yanchor e) {
    switch(e) {
        case Yanchor::TOP: return "top";
        case Yanchor::MIDDLE: return "middle";
        case Yanchor::BOTTOM: return "bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Line::Colorbar::to_string(Yref e) {
    switch(e) {
        case Yref::CONTAINER: return "container";
        case Yref::PAPER: return "paper";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::borderwidth(double f) {
    json["borderwidth"] = std::move(f);
    return *this;
}

template <typename T>
Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::dtick(T f) {
    json["dtick"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::exponentformat(enum Exponentformat f) {
    json["exponentformat"] = to_string(f);
    return *this;
}

template <typename T>
Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::labelalias(T f) {
    json["labelalias"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::len(double f) {
    json["len"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::lenmode(enum Lenmode f) {
    json["lenmode"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::minexponent(double f) {
    json["minexponent"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::nticks(int f) {
    json["nticks"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::orientation(enum Orientation f) {
    json["orientation"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::outlinecolor(std::string f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}
Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::outlinecolor(double f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::outlinewidth(double f) {
    json["outlinewidth"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::separatethousands(bool f) {
    json["separatethousands"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::showexponent(enum Showexponent f) {
    json["showexponent"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::showticklabels(bool f) {
    json["showticklabels"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::showtickprefix(enum Showtickprefix f) {
    json["showtickprefix"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::showticksuffix(enum Showticksuffix f) {
    json["showticksuffix"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::thickness(double f) {
    json["thickness"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::thicknessmode(enum Thicknessmode f) {
    json["thicknessmode"] = to_string(f);
    return *this;
}

template <typename T>
Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::tick0(T f) {
    json["tick0"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::tickangle(double f) {
    json["tickangle"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::tickcolor(std::string f) {
    json["tickcolor"] = std::move(f);
    return *this;
}
Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::tickcolor(double f) {
    json["tickcolor"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::tickfont(Tickfont f) {
    json["tickfont"] = std::move(f.json);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::tickformat(std::string f) {
    json["tickformat"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::tickformatstops(Tickformatstops f) {
    json["tickformatstops"] = std::move(f.json);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::ticklabeloverflow(enum Ticklabeloverflow f) {
    json["ticklabeloverflow"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::ticklabelposition(enum Ticklabelposition f) {
    json["ticklabelposition"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::ticklabelstep(int f) {
    json["ticklabelstep"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::ticklen(double f) {
    json["ticklen"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::tickmode(enum Tickmode f) {
    json["tickmode"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::tickprefix(std::string f) {
    json["tickprefix"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::ticks(enum Ticks f) {
    json["ticks"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::ticksuffix(std::string f) {
    json["ticksuffix"] = std::move(f);
    return *this;
}

template <typename T, typename>
Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::ticktext(std::vector<T> f) {
    json["ticktext"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::ticktextsrc(std::string f) {
    json["ticktextsrc"] = std::move(f);
    return *this;
}

template <typename T, typename>
Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::tickvals(std::vector<T> f) {
    json["tickvals"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::tickvalssrc(std::string f) {
    json["tickvalssrc"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::tickwidth(double f) {
    json["tickwidth"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::title(Title f) {
    json["title"] = std::move(f.json);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::x(double f) {
    json["x"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::xanchor(enum Xanchor f) {
    json["xanchor"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::xpad(double f) {
    json["xpad"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::xref(enum Xref f) {
    json["xref"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::y(double f) {
    json["y"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::yanchor(enum Yanchor f) {
    json["yanchor"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::ypad(double f) {
    json["ypad"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar& Scatter3D::Line::Colorbar::yref(enum Yref f) {
    json["yref"] = to_string(f);
    return *this;
}

std::string Scatter3D::Line::Colorbar::Tickfont::to_string(Style e) {
    switch(e) {
        case Style::NORMAL: return "normal";
        case Style::ITALIC: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Line::Colorbar::Tickfont::to_string(Textcase e) {
    switch(e) {
        case Textcase::NORMAL: return "normal";
        case Textcase::WORD_CAPS: return "word caps";
        case Textcase::UPPER: return "upper";
        case Textcase::LOWER: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Line::Colorbar::Tickfont::to_string(Variant e) {
    switch(e) {
        case Variant::NORMAL: return "normal";
        case Variant::SMALL_CAPS: return "small-caps";
        case Variant::ALL_SMALL_CAPS: return "all-small-caps";
        case Variant::ALL_PETITE_CAPS: return "all-petite-caps";
        case Variant::PETITE_CAPS: return "petite-caps";
        case Variant::UNICASE: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scatter3D::Line::Colorbar::Tickfont& Scatter3D::Line::Colorbar::Tickfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Line::Colorbar::Tickfont& Scatter3D::Line::Colorbar::Tickfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar::Tickfont& Scatter3D::Line::Colorbar::Tickfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar::Tickfont& Scatter3D::Line::Colorbar::Tickfont::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar::Tickfont& Scatter3D::Line::Colorbar::Tickfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar::Tickfont& Scatter3D::Line::Colorbar::Tickfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar::Tickfont& Scatter3D::Line::Colorbar::Tickfont::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar::Tickfont& Scatter3D::Line::Colorbar::Tickfont::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar::Tickfont& Scatter3D::Line::Colorbar::Tickfont::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar::Tickfont& Scatter3D::Line::Colorbar::Tickfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


Scatter3D::Line::Colorbar::Tickformatstops& Scatter3D::Line::Colorbar::Tickformatstops::tickformatstop(Tickformatstop f) {
    json["tickformatstop"] = std::move(f.json);
    return *this;
}


Scatter3D::Line::Colorbar::Tickformatstops::Tickformatstop& Scatter3D::Line::Colorbar::Tickformatstops::Tickformatstop::dtickrange(std::vector<std::string> f) {
    json["dtickrange"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar::Tickformatstops::Tickformatstop& Scatter3D::Line::Colorbar::Tickformatstops::Tickformatstop::enabled(bool f) {
    json["enabled"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar::Tickformatstops::Tickformatstop& Scatter3D::Line::Colorbar::Tickformatstops::Tickformatstop::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar::Tickformatstops::Tickformatstop& Scatter3D::Line::Colorbar::Tickformatstops::Tickformatstop::templateitemname(std::string f) {
    json["templateitemname"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar::Tickformatstops::Tickformatstop& Scatter3D::Line::Colorbar::Tickformatstops::Tickformatstop::value(std::string f) {
    json["value"] = std::move(f);
    return *this;
}

std::string Scatter3D::Line::Colorbar::Title::to_string(Side e) {
    switch(e) {
        case Side::RIGHT: return "right";
        case Side::TOP: return "top";
        case Side::BOTTOM: return "bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scatter3D::Line::Colorbar::Title& Scatter3D::Line::Colorbar::Title::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}

Scatter3D::Line::Colorbar::Title& Scatter3D::Line::Colorbar::Title::side(enum Side f) {
    json["side"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar::Title& Scatter3D::Line::Colorbar::Title::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

std::string Scatter3D::Line::Colorbar::Title::Font::to_string(Style e) {
    switch(e) {
        case Style::NORMAL: return "normal";
        case Style::ITALIC: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Line::Colorbar::Title::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::NORMAL: return "normal";
        case Textcase::WORD_CAPS: return "word caps";
        case Textcase::UPPER: return "upper";
        case Textcase::LOWER: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Line::Colorbar::Title::Font::to_string(Variant e) {
    switch(e) {
        case Variant::NORMAL: return "normal";
        case Variant::SMALL_CAPS: return "small-caps";
        case Variant::ALL_SMALL_CAPS: return "all-small-caps";
        case Variant::ALL_PETITE_CAPS: return "all-petite-caps";
        case Variant::PETITE_CAPS: return "petite-caps";
        case Variant::UNICASE: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scatter3D::Line::Colorbar::Title::Font& Scatter3D::Line::Colorbar::Title::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Line::Colorbar::Title::Font& Scatter3D::Line::Colorbar::Title::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar::Title::Font& Scatter3D::Line::Colorbar::Title::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar::Title::Font& Scatter3D::Line::Colorbar::Title::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar::Title::Font& Scatter3D::Line::Colorbar::Title::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar::Title::Font& Scatter3D::Line::Colorbar::Title::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

Scatter3D::Line::Colorbar::Title::Font& Scatter3D::Line::Colorbar::Title::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar::Title::Font& Scatter3D::Line::Colorbar::Title::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar::Title::Font& Scatter3D::Line::Colorbar::Title::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

Scatter3D::Line::Colorbar::Title::Font& Scatter3D::Line::Colorbar::Title::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}

std::string Scatter3D::Marker::to_string(Sizemode e) {
    switch(e) {
        case Sizemode::DIAMETER: return "diameter";
        case Sizemode::AREA: return "area";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::to_string(Symbol e) {
    switch(e) {
        case Symbol::CIRCLE: return "circle";
        case Symbol::CIRCLE_OPEN: return "circle-open";
        case Symbol::CROSS: return "cross";
        case Symbol::DIAMOND: return "diamond";
        case Symbol::DIAMOND_OPEN: return "diamond-open";
        case Symbol::SQUARE: return "square";
        case Symbol::SQUARE_OPEN: return "square-open";
        case Symbol::X: return "x";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scatter3D::Marker& Scatter3D::Marker::autocolorscale(bool f) {
    json["autocolorscale"] = std::move(f);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::cauto(bool f) {
    json["cauto"] = std::move(f);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::cmax(double f) {
    json["cmax"] = std::move(f);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::cmid(double f) {
    json["cmid"] = std::move(f);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::cmin(double f) {
    json["cmin"] = std::move(f);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Marker& Scatter3D::Marker::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Marker& Scatter3D::Marker::color(std::vector<std::string> f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Marker& Scatter3D::Marker::color(std::vector<double> f) {
    json["color"] = std::move(f);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::coloraxis(std::string f) {
    json["coloraxis"] = std::move(f);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::colorbar(Colorbar f) {
    json["colorbar"] = std::move(f.json);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::colorscale(std::string f) {
    json["colorscale"] = std::move(f);
    return *this;
}
Scatter3D::Marker& Scatter3D::Marker::colorscale(std::vector<std::pair<double, std::string>> f) {
    json["colorscale"] = std::move(f);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::line(Line f) {
    json["line"] = std::move(f.json);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::reversescale(bool f) {
    json["reversescale"] = std::move(f);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::showscale(bool f) {
    json["showscale"] = std::move(f);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
Scatter3D::Marker& Scatter3D::Marker::size(std::vector<double> f) {
    json["size"] = std::move(f);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::sizemin(double f) {
    json["sizemin"] = std::move(f);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::sizemode(enum Sizemode f) {
    json["sizemode"] = to_string(f);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::sizeref(double f) {
    json["sizeref"] = std::move(f);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::symbol(enum Symbol f) {
    json["symbol"] = to_string(f);
    return *this;
}
Scatter3D::Marker& Scatter3D::Marker::symbol(const std::vector<enum Symbol>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["symbol"] = std::move(stringified);
    return *this;
}

Scatter3D::Marker& Scatter3D::Marker::symbolsrc(std::string f) {
    json["symbolsrc"] = std::move(f);
    return *this;
}

std::string Scatter3D::Marker::Colorbar::to_string(Exponentformat e) {
    switch(e) {
        case Exponentformat::NONE: return "none";
        case Exponentformat::E: return "E";
        case Exponentformat::POWER: return "power";
        case Exponentformat::SI: return "SI";
        case Exponentformat::B: return "B";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::Colorbar::to_string(Lenmode e) {
    switch(e) {
        case Lenmode::FRACTION: return "fraction";
        case Lenmode::PIXELS: return "pixels";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::Colorbar::to_string(Orientation e) {
    switch(e) {
        case Orientation::H: return "h";
        case Orientation::V: return "v";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::Colorbar::to_string(Showexponent e) {
    switch(e) {
        case Showexponent::ALL: return "all";
        case Showexponent::FIRST: return "first";
        case Showexponent::LAST: return "last";
        case Showexponent::NONE: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::Colorbar::to_string(Showtickprefix e) {
    switch(e) {
        case Showtickprefix::ALL: return "all";
        case Showtickprefix::FIRST: return "first";
        case Showtickprefix::LAST: return "last";
        case Showtickprefix::NONE: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::Colorbar::to_string(Showticksuffix e) {
    switch(e) {
        case Showticksuffix::ALL: return "all";
        case Showticksuffix::FIRST: return "first";
        case Showticksuffix::LAST: return "last";
        case Showticksuffix::NONE: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::Colorbar::to_string(Thicknessmode e) {
    switch(e) {
        case Thicknessmode::FRACTION: return "fraction";
        case Thicknessmode::PIXELS: return "pixels";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::Colorbar::to_string(Ticklabeloverflow e) {
    switch(e) {
        case Ticklabeloverflow::ALLOW: return "allow";
        case Ticklabeloverflow::HIDE_PAST_DIV: return "hide past div";
        case Ticklabeloverflow::HIDE_PAST_DOMAIN: return "hide past domain";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::Colorbar::to_string(Ticklabelposition e) {
    switch(e) {
        case Ticklabelposition::OUTSIDE: return "outside";
        case Ticklabelposition::INSIDE: return "inside";
        case Ticklabelposition::OUTSIDE_TOP: return "outside top";
        case Ticklabelposition::INSIDE_TOP: return "inside top";
        case Ticklabelposition::OUTSIDE_LEFT: return "outside left";
        case Ticklabelposition::INSIDE_LEFT: return "inside left";
        case Ticklabelposition::OUTSIDE_RIGHT: return "outside right";
        case Ticklabelposition::INSIDE_RIGHT: return "inside right";
        case Ticklabelposition::OUTSIDE_BOTTOM: return "outside bottom";
        case Ticklabelposition::INSIDE_BOTTOM: return "inside bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::Colorbar::to_string(Tickmode e) {
    switch(e) {
        case Tickmode::AUTO: return "auto";
        case Tickmode::LINEAR: return "linear";
        case Tickmode::ARRAY: return "array";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::Colorbar::to_string(Ticks e) {
    switch(e) {
        case Ticks::OUTSIDE: return "outside";
        case Ticks::INSIDE: return "inside";
        case Ticks::EMPTY: return "";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::Colorbar::to_string(Xanchor e) {
    switch(e) {
        case Xanchor::LEFT: return "left";
        case Xanchor::CENTER: return "center";
        case Xanchor::RIGHT: return "right";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::Colorbar::to_string(Xref e) {
    switch(e) {
        case Xref::CONTAINER: return "container";
        case Xref::PAPER: return "paper";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::Colorbar::to_string(Yanchor e) {
    switch(e) {
        case Yanchor::TOP: return "top";
        case Yanchor::MIDDLE: return "middle";
        case Yanchor::BOTTOM: return "bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::Colorbar::to_string(Yref e) {
    switch(e) {
        case Yref::CONTAINER: return "container";
        case Yref::PAPER: return "paper";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::borderwidth(double f) {
    json["borderwidth"] = std::move(f);
    return *this;
}

template <typename T>
Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::dtick(T f) {
    json["dtick"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::exponentformat(enum Exponentformat f) {
    json["exponentformat"] = to_string(f);
    return *this;
}

template <typename T>
Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::labelalias(T f) {
    json["labelalias"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::len(double f) {
    json["len"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::lenmode(enum Lenmode f) {
    json["lenmode"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::minexponent(double f) {
    json["minexponent"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::nticks(int f) {
    json["nticks"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::orientation(enum Orientation f) {
    json["orientation"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::outlinecolor(std::string f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}
Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::outlinecolor(double f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::outlinewidth(double f) {
    json["outlinewidth"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::separatethousands(bool f) {
    json["separatethousands"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::showexponent(enum Showexponent f) {
    json["showexponent"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::showticklabels(bool f) {
    json["showticklabels"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::showtickprefix(enum Showtickprefix f) {
    json["showtickprefix"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::showticksuffix(enum Showticksuffix f) {
    json["showticksuffix"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::thickness(double f) {
    json["thickness"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::thicknessmode(enum Thicknessmode f) {
    json["thicknessmode"] = to_string(f);
    return *this;
}

template <typename T>
Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::tick0(T f) {
    json["tick0"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::tickangle(double f) {
    json["tickangle"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::tickcolor(std::string f) {
    json["tickcolor"] = std::move(f);
    return *this;
}
Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::tickcolor(double f) {
    json["tickcolor"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::tickfont(Tickfont f) {
    json["tickfont"] = std::move(f.json);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::tickformat(std::string f) {
    json["tickformat"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::tickformatstops(Tickformatstops f) {
    json["tickformatstops"] = std::move(f.json);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::ticklabeloverflow(enum Ticklabeloverflow f) {
    json["ticklabeloverflow"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::ticklabelposition(enum Ticklabelposition f) {
    json["ticklabelposition"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::ticklabelstep(int f) {
    json["ticklabelstep"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::ticklen(double f) {
    json["ticklen"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::tickmode(enum Tickmode f) {
    json["tickmode"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::tickprefix(std::string f) {
    json["tickprefix"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::ticks(enum Ticks f) {
    json["ticks"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::ticksuffix(std::string f) {
    json["ticksuffix"] = std::move(f);
    return *this;
}

template <typename T, typename>
Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::ticktext(std::vector<T> f) {
    json["ticktext"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::ticktextsrc(std::string f) {
    json["ticktextsrc"] = std::move(f);
    return *this;
}

template <typename T, typename>
Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::tickvals(std::vector<T> f) {
    json["tickvals"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::tickvalssrc(std::string f) {
    json["tickvalssrc"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::tickwidth(double f) {
    json["tickwidth"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::title(Title f) {
    json["title"] = std::move(f.json);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::x(double f) {
    json["x"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::xanchor(enum Xanchor f) {
    json["xanchor"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::xpad(double f) {
    json["xpad"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::xref(enum Xref f) {
    json["xref"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::y(double f) {
    json["y"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::yanchor(enum Yanchor f) {
    json["yanchor"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::ypad(double f) {
    json["ypad"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar& Scatter3D::Marker::Colorbar::yref(enum Yref f) {
    json["yref"] = to_string(f);
    return *this;
}

std::string Scatter3D::Marker::Colorbar::Tickfont::to_string(Style e) {
    switch(e) {
        case Style::NORMAL: return "normal";
        case Style::ITALIC: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::Colorbar::Tickfont::to_string(Textcase e) {
    switch(e) {
        case Textcase::NORMAL: return "normal";
        case Textcase::WORD_CAPS: return "word caps";
        case Textcase::UPPER: return "upper";
        case Textcase::LOWER: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::Colorbar::Tickfont::to_string(Variant e) {
    switch(e) {
        case Variant::NORMAL: return "normal";
        case Variant::SMALL_CAPS: return "small-caps";
        case Variant::ALL_SMALL_CAPS: return "all-small-caps";
        case Variant::ALL_PETITE_CAPS: return "all-petite-caps";
        case Variant::PETITE_CAPS: return "petite-caps";
        case Variant::UNICASE: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scatter3D::Marker::Colorbar::Tickfont& Scatter3D::Marker::Colorbar::Tickfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Marker::Colorbar::Tickfont& Scatter3D::Marker::Colorbar::Tickfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Tickfont& Scatter3D::Marker::Colorbar::Tickfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Tickfont& Scatter3D::Marker::Colorbar::Tickfont::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Tickfont& Scatter3D::Marker::Colorbar::Tickfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Tickfont& Scatter3D::Marker::Colorbar::Tickfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Tickfont& Scatter3D::Marker::Colorbar::Tickfont::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Tickfont& Scatter3D::Marker::Colorbar::Tickfont::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Tickfont& Scatter3D::Marker::Colorbar::Tickfont::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Tickfont& Scatter3D::Marker::Colorbar::Tickfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


Scatter3D::Marker::Colorbar::Tickformatstops& Scatter3D::Marker::Colorbar::Tickformatstops::tickformatstop(Tickformatstop f) {
    json["tickformatstop"] = std::move(f.json);
    return *this;
}


Scatter3D::Marker::Colorbar::Tickformatstops::Tickformatstop& Scatter3D::Marker::Colorbar::Tickformatstops::Tickformatstop::dtickrange(std::vector<std::string> f) {
    json["dtickrange"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Tickformatstops::Tickformatstop& Scatter3D::Marker::Colorbar::Tickformatstops::Tickformatstop::enabled(bool f) {
    json["enabled"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Tickformatstops::Tickformatstop& Scatter3D::Marker::Colorbar::Tickformatstops::Tickformatstop::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Tickformatstops::Tickformatstop& Scatter3D::Marker::Colorbar::Tickformatstops::Tickformatstop::templateitemname(std::string f) {
    json["templateitemname"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Tickformatstops::Tickformatstop& Scatter3D::Marker::Colorbar::Tickformatstops::Tickformatstop::value(std::string f) {
    json["value"] = std::move(f);
    return *this;
}

std::string Scatter3D::Marker::Colorbar::Title::to_string(Side e) {
    switch(e) {
        case Side::RIGHT: return "right";
        case Side::TOP: return "top";
        case Side::BOTTOM: return "bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scatter3D::Marker::Colorbar::Title& Scatter3D::Marker::Colorbar::Title::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}

Scatter3D::Marker::Colorbar::Title& Scatter3D::Marker::Colorbar::Title::side(enum Side f) {
    json["side"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Title& Scatter3D::Marker::Colorbar::Title::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

std::string Scatter3D::Marker::Colorbar::Title::Font::to_string(Style e) {
    switch(e) {
        case Style::NORMAL: return "normal";
        case Style::ITALIC: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::Colorbar::Title::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::NORMAL: return "normal";
        case Textcase::WORD_CAPS: return "word caps";
        case Textcase::UPPER: return "upper";
        case Textcase::LOWER: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Marker::Colorbar::Title::Font::to_string(Variant e) {
    switch(e) {
        case Variant::NORMAL: return "normal";
        case Variant::SMALL_CAPS: return "small-caps";
        case Variant::ALL_SMALL_CAPS: return "all-small-caps";
        case Variant::ALL_PETITE_CAPS: return "all-petite-caps";
        case Variant::PETITE_CAPS: return "petite-caps";
        case Variant::UNICASE: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scatter3D::Marker::Colorbar::Title::Font& Scatter3D::Marker::Colorbar::Title::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Marker::Colorbar::Title::Font& Scatter3D::Marker::Colorbar::Title::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Title::Font& Scatter3D::Marker::Colorbar::Title::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Title::Font& Scatter3D::Marker::Colorbar::Title::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Title::Font& Scatter3D::Marker::Colorbar::Title::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Title::Font& Scatter3D::Marker::Colorbar::Title::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Title::Font& Scatter3D::Marker::Colorbar::Title::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Title::Font& Scatter3D::Marker::Colorbar::Title::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Title::Font& Scatter3D::Marker::Colorbar::Title::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

Scatter3D::Marker::Colorbar::Title::Font& Scatter3D::Marker::Colorbar::Title::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


Scatter3D::Marker::Line& Scatter3D::Marker::Line::autocolorscale(bool f) {
    json["autocolorscale"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Line& Scatter3D::Marker::Line::cauto(bool f) {
    json["cauto"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Line& Scatter3D::Marker::Line::cmax(double f) {
    json["cmax"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Line& Scatter3D::Marker::Line::cmid(double f) {
    json["cmid"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Line& Scatter3D::Marker::Line::cmin(double f) {
    json["cmin"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Line& Scatter3D::Marker::Line::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Marker::Line& Scatter3D::Marker::Line::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Marker::Line& Scatter3D::Marker::Line::color(std::vector<std::string> f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Marker::Line& Scatter3D::Marker::Line::color(std::vector<double> f) {
    json["color"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Line& Scatter3D::Marker::Line::coloraxis(std::string f) {
    json["coloraxis"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Line& Scatter3D::Marker::Line::colorscale(std::string f) {
    json["colorscale"] = std::move(f);
    return *this;
}
Scatter3D::Marker::Line& Scatter3D::Marker::Line::colorscale(std::vector<std::pair<double, std::string>> f) {
    json["colorscale"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Line& Scatter3D::Marker::Line::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Line& Scatter3D::Marker::Line::reversescale(bool f) {
    json["reversescale"] = std::move(f);
    return *this;
}

Scatter3D::Marker::Line& Scatter3D::Marker::Line::width(double f) {
    json["width"] = std::move(f);
    return *this;
}


Scatter3D::Projection& Scatter3D::Projection::x(X f) {
    json["x"] = std::move(f.json);
    return *this;
}

Scatter3D::Projection& Scatter3D::Projection::y(Y f) {
    json["y"] = std::move(f.json);
    return *this;
}

Scatter3D::Projection& Scatter3D::Projection::z(Z f) {
    json["z"] = std::move(f.json);
    return *this;
}


Scatter3D::Projection::X& Scatter3D::Projection::X::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}

Scatter3D::Projection::X& Scatter3D::Projection::X::scale(double f) {
    json["scale"] = std::move(f);
    return *this;
}

Scatter3D::Projection::X& Scatter3D::Projection::X::show(bool f) {
    json["show"] = std::move(f);
    return *this;
}


Scatter3D::Projection::Y& Scatter3D::Projection::Y::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}

Scatter3D::Projection::Y& Scatter3D::Projection::Y::scale(double f) {
    json["scale"] = std::move(f);
    return *this;
}

Scatter3D::Projection::Y& Scatter3D::Projection::Y::show(bool f) {
    json["show"] = std::move(f);
    return *this;
}


Scatter3D::Projection::Z& Scatter3D::Projection::Z::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}

Scatter3D::Projection::Z& Scatter3D::Projection::Z::scale(double f) {
    json["scale"] = std::move(f);
    return *this;
}

Scatter3D::Projection::Z& Scatter3D::Projection::Z::show(bool f) {
    json["show"] = std::move(f);
    return *this;
}


Scatter3D::Stream& Scatter3D::Stream::maxpoints(double f) {
    json["maxpoints"] = std::move(f);
    return *this;
}

Scatter3D::Stream& Scatter3D::Stream::token(std::string f) {
    json["token"] = std::move(f);
    return *this;
}

std::string Scatter3D::Textfont::to_string(Style e) {
    switch(e) {
        case Style::NORMAL: return "normal";
        case Style::ITALIC: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scatter3D::Textfont::to_string(Variant e) {
    switch(e) {
        case Variant::NORMAL: return "normal";
        case Variant::SMALL_CAPS: return "small-caps";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scatter3D::Textfont& Scatter3D::Textfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Textfont& Scatter3D::Textfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Textfont& Scatter3D::Textfont::color(std::vector<std::string> f) {
    json["color"] = std::move(f);
    return *this;
}
Scatter3D::Textfont& Scatter3D::Textfont::color(std::vector<double> f) {
    json["color"] = std::move(f);
    return *this;
}

Scatter3D::Textfont& Scatter3D::Textfont::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

Scatter3D::Textfont& Scatter3D::Textfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
Scatter3D::Textfont& Scatter3D::Textfont::family(std::vector<std::string> f) {
    json["family"] = std::move(f);
    return *this;
}

Scatter3D::Textfont& Scatter3D::Textfont::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

Scatter3D::Textfont& Scatter3D::Textfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
Scatter3D::Textfont& Scatter3D::Textfont::size(std::vector<double> f) {
    json["size"] = std::move(f);
    return *this;
}

Scatter3D::Textfont& Scatter3D::Textfont::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

Scatter3D::Textfont& Scatter3D::Textfont::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}
Scatter3D::Textfont& Scatter3D::Textfont::style(const std::vector<enum Style>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["style"] = std::move(stringified);
    return *this;
}

Scatter3D::Textfont& Scatter3D::Textfont::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

Scatter3D::Textfont& Scatter3D::Textfont::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}
Scatter3D::Textfont& Scatter3D::Textfont::variant(const std::vector<enum Variant>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["variant"] = std::move(stringified);
    return *this;
}

Scatter3D::Textfont& Scatter3D::Textfont::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

Scatter3D::Textfont& Scatter3D::Textfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
Scatter3D::Textfont& Scatter3D::Textfont::weight(std::vector<int> f) {
    json["weight"] = std::move(f);
    return *this;
}

Scatter3D::Textfont& Scatter3D::Textfont::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}

} // namespace plotlypp

