// Copyright (c) 2025 Jimmy O'Rourke
// Licensed under and subject to the terms of the LICENSE file accompanying this distribution.
// Official repository: https://github.com/jimmyorourke/plotlypp

// Autogenerated by plotlypp/generator, from official Plotly sources.
// See https://plotly.com/graphing-libraries.
// Do not edit, changes may be overwritten!

#pragma once

namespace plotlypp {

std::string Scattermap::to_string(Fill e) {
    switch(e) {
        case Fill::NONE: return "none";
        case Fill::TOSELF: return "toself";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::to_string(Textposition e) {
    switch(e) {
        case Textposition::TOP_LEFT: return "top left";
        case Textposition::TOP_CENTER: return "top center";
        case Textposition::TOP_RIGHT: return "top right";
        case Textposition::MIDDLE_LEFT: return "middle left";
        case Textposition::MIDDLE_CENTER: return "middle center";
        case Textposition::MIDDLE_RIGHT: return "middle right";
        case Textposition::BOTTOM_LEFT: return "bottom left";
        case Textposition::BOTTOM_CENTER: return "bottom center";
        case Textposition::BOTTOM_RIGHT: return "bottom right";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::to_string(Visible e) {
    switch(e) {
        case Visible::TRUE: return "True";
        case Visible::FALSE: return "False";
        case Visible::LEGENDONLY: return "legendonly";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scattermap& Scattermap::below(std::string f) {
    json["below"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::cluster(Cluster f) {
    json["cluster"] = std::move(f.json);
    return *this;
}

Scattermap& Scattermap::connectgaps(bool f) {
    json["connectgaps"] = std::move(f);
    return *this;
}

template <typename T, typename>
Scattermap& Scattermap::customdata(std::vector<T> f) {
    json["customdata"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::customdatasrc(std::string f) {
    json["customdatasrc"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::fill(enum Fill f) {
    json["fill"] = to_string(f);
    return *this;
}

Scattermap& Scattermap::fillcolor(std::string f) {
    json["fillcolor"] = std::move(f);
    return *this;
}
Scattermap& Scattermap::fillcolor(double f) {
    json["fillcolor"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::hoverinfo(std::string f) {
    json["hoverinfo"] = std::move(f);
    return *this;
}
Scattermap& Scattermap::hoverinfo(std::vector<std::string> f) {
    json["hoverinfo"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::hoverinfosrc(std::string f) {
    json["hoverinfosrc"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::hoverlabel(Hoverlabel f) {
    json["hoverlabel"] = std::move(f.json);
    return *this;
}

Scattermap& Scattermap::hovertemplate(std::string f) {
    json["hovertemplate"] = std::move(f);
    return *this;
}
Scattermap& Scattermap::hovertemplate(std::vector<std::string> f) {
    json["hovertemplate"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::hovertemplatesrc(std::string f) {
    json["hovertemplatesrc"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::hovertext(std::string f) {
    json["hovertext"] = std::move(f);
    return *this;
}
Scattermap& Scattermap::hovertext(std::vector<std::string> f) {
    json["hovertext"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::hovertextsrc(std::string f) {
    json["hovertextsrc"] = std::move(f);
    return *this;
}

template <typename T, typename>
Scattermap& Scattermap::ids(std::vector<T> f) {
    json["ids"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::idssrc(std::string f) {
    json["idssrc"] = std::move(f);
    return *this;
}

template <typename T, typename>
Scattermap& Scattermap::lat(std::vector<T> f) {
    json["lat"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::latsrc(std::string f) {
    json["latsrc"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::legend(std::string f) {
    json["legend"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::legendgroup(std::string f) {
    json["legendgroup"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::legendgrouptitle(Legendgrouptitle f) {
    json["legendgrouptitle"] = std::move(f.json);
    return *this;
}

Scattermap& Scattermap::legendrank(double f) {
    json["legendrank"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::legendwidth(double f) {
    json["legendwidth"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::line(Line f) {
    json["line"] = std::move(f.json);
    return *this;
}

template <typename T, typename>
Scattermap& Scattermap::lon(std::vector<T> f) {
    json["lon"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::lonsrc(std::string f) {
    json["lonsrc"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::marker(Marker f) {
    json["marker"] = std::move(f.json);
    return *this;
}

template <typename T>
Scattermap& Scattermap::meta(T f) {
    json["meta"] = std::move(f);
    return *this;
}
template <typename T>
Scattermap& Scattermap::meta(std::vector<T> f) {
    json["meta"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::metasrc(std::string f) {
    json["metasrc"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::mode(std::string f) {
    json["mode"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::selected(Selected f) {
    json["selected"] = std::move(f.json);
    return *this;
}

template <typename T>
Scattermap& Scattermap::selectedpoints(T f) {
    json["selectedpoints"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::showlegend(bool f) {
    json["showlegend"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::stream(Stream f) {
    json["stream"] = std::move(f.json);
    return *this;
}

Scattermap& Scattermap::subplot(std::string f) {
    json["subplot"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}
Scattermap& Scattermap::text(std::vector<std::string> f) {
    json["text"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::textfont(Textfont f) {
    json["textfont"] = std::move(f.json);
    return *this;
}

Scattermap& Scattermap::textposition(enum Textposition f) {
    json["textposition"] = to_string(f);
    return *this;
}

Scattermap& Scattermap::textsrc(std::string f) {
    json["textsrc"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::texttemplate(std::string f) {
    json["texttemplate"] = std::move(f);
    return *this;
}
Scattermap& Scattermap::texttemplate(std::vector<std::string> f) {
    json["texttemplate"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::texttemplatesrc(std::string f) {
    json["texttemplatesrc"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::uid(std::string f) {
    json["uid"] = std::move(f);
    return *this;
}

template <typename T>
Scattermap& Scattermap::uirevision(T f) {
    json["uirevision"] = std::move(f);
    return *this;
}

Scattermap& Scattermap::unselected(Unselected f) {
    json["unselected"] = std::move(f.json);
    return *this;
}

Scattermap& Scattermap::visible(enum Visible f) {
    json["visible"] = to_string(f);
    return *this;
}


Scattermap::Cluster& Scattermap::Cluster::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scattermap::Cluster& Scattermap::Cluster::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
Scattermap::Cluster& Scattermap::Cluster::color(std::vector<std::string> f) {
    json["color"] = std::move(f);
    return *this;
}
Scattermap::Cluster& Scattermap::Cluster::color(std::vector<double> f) {
    json["color"] = std::move(f);
    return *this;
}

Scattermap::Cluster& Scattermap::Cluster::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

Scattermap::Cluster& Scattermap::Cluster::enabled(bool f) {
    json["enabled"] = std::move(f);
    return *this;
}

Scattermap::Cluster& Scattermap::Cluster::maxzoom(double f) {
    json["maxzoom"] = std::move(f);
    return *this;
}

Scattermap::Cluster& Scattermap::Cluster::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}
Scattermap::Cluster& Scattermap::Cluster::opacity(std::vector<double> f) {
    json["opacity"] = std::move(f);
    return *this;
}

Scattermap::Cluster& Scattermap::Cluster::opacitysrc(std::string f) {
    json["opacitysrc"] = std::move(f);
    return *this;
}

Scattermap::Cluster& Scattermap::Cluster::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
Scattermap::Cluster& Scattermap::Cluster::size(std::vector<double> f) {
    json["size"] = std::move(f);
    return *this;
}

Scattermap::Cluster& Scattermap::Cluster::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

Scattermap::Cluster& Scattermap::Cluster::step(double f) {
    json["step"] = std::move(f);
    return *this;
}
Scattermap::Cluster& Scattermap::Cluster::step(std::vector<double> f) {
    json["step"] = std::move(f);
    return *this;
}

Scattermap::Cluster& Scattermap::Cluster::stepsrc(std::string f) {
    json["stepsrc"] = std::move(f);
    return *this;
}

std::string Scattermap::Hoverlabel::to_string(Align e) {
    switch(e) {
        case Align::LEFT: return "left";
        case Align::RIGHT: return "right";
        case Align::AUTO: return "auto";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scattermap::Hoverlabel& Scattermap::Hoverlabel::align(enum Align f) {
    json["align"] = to_string(f);
    return *this;
}
Scattermap::Hoverlabel& Scattermap::Hoverlabel::align(const std::vector<enum Align>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["align"] = std::move(stringified);
    return *this;
}

Scattermap::Hoverlabel& Scattermap::Hoverlabel::alignsrc(std::string f) {
    json["alignsrc"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel& Scattermap::Hoverlabel::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
Scattermap::Hoverlabel& Scattermap::Hoverlabel::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
Scattermap::Hoverlabel& Scattermap::Hoverlabel::bgcolor(std::vector<std::string> f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
Scattermap::Hoverlabel& Scattermap::Hoverlabel::bgcolor(std::vector<double> f) {
    json["bgcolor"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel& Scattermap::Hoverlabel::bgcolorsrc(std::string f) {
    json["bgcolorsrc"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel& Scattermap::Hoverlabel::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
Scattermap::Hoverlabel& Scattermap::Hoverlabel::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
Scattermap::Hoverlabel& Scattermap::Hoverlabel::bordercolor(std::vector<std::string> f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
Scattermap::Hoverlabel& Scattermap::Hoverlabel::bordercolor(std::vector<double> f) {
    json["bordercolor"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel& Scattermap::Hoverlabel::bordercolorsrc(std::string f) {
    json["bordercolorsrc"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel& Scattermap::Hoverlabel::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}

Scattermap::Hoverlabel& Scattermap::Hoverlabel::namelength(int f) {
    json["namelength"] = std::move(f);
    return *this;
}
Scattermap::Hoverlabel& Scattermap::Hoverlabel::namelength(std::vector<int> f) {
    json["namelength"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel& Scattermap::Hoverlabel::namelengthsrc(std::string f) {
    json["namelengthsrc"] = std::move(f);
    return *this;
}

std::string Scattermap::Hoverlabel::Font::to_string(Style e) {
    switch(e) {
        case Style::NORMAL: return "normal";
        case Style::ITALIC: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Hoverlabel::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::NORMAL: return "normal";
        case Textcase::WORD_CAPS: return "word caps";
        case Textcase::UPPER: return "upper";
        case Textcase::LOWER: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Hoverlabel::Font::to_string(Variant e) {
    switch(e) {
        case Variant::NORMAL: return "normal";
        case Variant::SMALL_CAPS: return "small-caps";
        case Variant::ALL_SMALL_CAPS: return "all-small-caps";
        case Variant::ALL_PETITE_CAPS: return "all-petite-caps";
        case Variant::PETITE_CAPS: return "petite-caps";
        case Variant::UNICASE: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::color(std::vector<std::string> f) {
    json["color"] = std::move(f);
    return *this;
}
Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::color(std::vector<double> f) {
    json["color"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::family(std::vector<std::string> f) {
    json["family"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}
Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::lineposition(std::vector<std::string> f) {
    json["lineposition"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::linepositionsrc(std::string f) {
    json["linepositionsrc"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}
Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::shadow(std::vector<std::string> f) {
    json["shadow"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::shadowsrc(std::string f) {
    json["shadowsrc"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::size(std::vector<double> f) {
    json["size"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}
Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::style(const std::vector<enum Style>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["style"] = std::move(stringified);
    return *this;
}

Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}
Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::textcase(const std::vector<enum Textcase>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["textcase"] = std::move(stringified);
    return *this;
}

Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::textcasesrc(std::string f) {
    json["textcasesrc"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}
Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::variant(const std::vector<enum Variant>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["variant"] = std::move(stringified);
    return *this;
}

Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::weight(std::vector<int> f) {
    json["weight"] = std::move(f);
    return *this;
}

Scattermap::Hoverlabel::Font& Scattermap::Hoverlabel::Font::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}


Scattermap::Legendgrouptitle& Scattermap::Legendgrouptitle::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}

Scattermap::Legendgrouptitle& Scattermap::Legendgrouptitle::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

std::string Scattermap::Legendgrouptitle::Font::to_string(Style e) {
    switch(e) {
        case Style::NORMAL: return "normal";
        case Style::ITALIC: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Legendgrouptitle::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::NORMAL: return "normal";
        case Textcase::WORD_CAPS: return "word caps";
        case Textcase::UPPER: return "upper";
        case Textcase::LOWER: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Legendgrouptitle::Font::to_string(Variant e) {
    switch(e) {
        case Variant::NORMAL: return "normal";
        case Variant::SMALL_CAPS: return "small-caps";
        case Variant::ALL_SMALL_CAPS: return "all-small-caps";
        case Variant::ALL_PETITE_CAPS: return "all-petite-caps";
        case Variant::PETITE_CAPS: return "petite-caps";
        case Variant::UNICASE: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scattermap::Legendgrouptitle::Font& Scattermap::Legendgrouptitle::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scattermap::Legendgrouptitle::Font& Scattermap::Legendgrouptitle::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

Scattermap::Legendgrouptitle::Font& Scattermap::Legendgrouptitle::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

Scattermap::Legendgrouptitle::Font& Scattermap::Legendgrouptitle::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

Scattermap::Legendgrouptitle::Font& Scattermap::Legendgrouptitle::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

Scattermap::Legendgrouptitle::Font& Scattermap::Legendgrouptitle::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

Scattermap::Legendgrouptitle::Font& Scattermap::Legendgrouptitle::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

Scattermap::Legendgrouptitle::Font& Scattermap::Legendgrouptitle::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

Scattermap::Legendgrouptitle::Font& Scattermap::Legendgrouptitle::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

Scattermap::Legendgrouptitle::Font& Scattermap::Legendgrouptitle::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


Scattermap::Line& Scattermap::Line::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scattermap::Line& Scattermap::Line::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

Scattermap::Line& Scattermap::Line::width(double f) {
    json["width"] = std::move(f);
    return *this;
}

std::string Scattermap::Marker::to_string(Sizemode e) {
    switch(e) {
        case Sizemode::DIAMETER: return "diameter";
        case Sizemode::AREA: return "area";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scattermap::Marker& Scattermap::Marker::allowoverlap(bool f) {
    json["allowoverlap"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::angle(double f) {
    json["angle"] = std::move(f);
    return *this;
}
Scattermap::Marker& Scattermap::Marker::angle(std::vector<double> f) {
    json["angle"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::anglesrc(std::string f) {
    json["anglesrc"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::autocolorscale(bool f) {
    json["autocolorscale"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::cauto(bool f) {
    json["cauto"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::cmax(double f) {
    json["cmax"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::cmid(double f) {
    json["cmid"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::cmin(double f) {
    json["cmin"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scattermap::Marker& Scattermap::Marker::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
Scattermap::Marker& Scattermap::Marker::color(std::vector<std::string> f) {
    json["color"] = std::move(f);
    return *this;
}
Scattermap::Marker& Scattermap::Marker::color(std::vector<double> f) {
    json["color"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::coloraxis(std::string f) {
    json["coloraxis"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::colorbar(Colorbar f) {
    json["colorbar"] = std::move(f.json);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::colorscale(std::string f) {
    json["colorscale"] = std::move(f);
    return *this;
}
Scattermap::Marker& Scattermap::Marker::colorscale(std::vector<std::pair<double, std::string>> f) {
    json["colorscale"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}
Scattermap::Marker& Scattermap::Marker::opacity(std::vector<double> f) {
    json["opacity"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::opacitysrc(std::string f) {
    json["opacitysrc"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::reversescale(bool f) {
    json["reversescale"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::showscale(bool f) {
    json["showscale"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
Scattermap::Marker& Scattermap::Marker::size(std::vector<double> f) {
    json["size"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::sizemin(double f) {
    json["sizemin"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::sizemode(enum Sizemode f) {
    json["sizemode"] = to_string(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::sizeref(double f) {
    json["sizeref"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::symbol(std::string f) {
    json["symbol"] = std::move(f);
    return *this;
}
Scattermap::Marker& Scattermap::Marker::symbol(std::vector<std::string> f) {
    json["symbol"] = std::move(f);
    return *this;
}

Scattermap::Marker& Scattermap::Marker::symbolsrc(std::string f) {
    json["symbolsrc"] = std::move(f);
    return *this;
}

std::string Scattermap::Marker::Colorbar::to_string(Exponentformat e) {
    switch(e) {
        case Exponentformat::NONE: return "none";
        case Exponentformat::E: return "E";
        case Exponentformat::POWER: return "power";
        case Exponentformat::SI: return "SI";
        case Exponentformat::B: return "B";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Marker::Colorbar::to_string(Lenmode e) {
    switch(e) {
        case Lenmode::FRACTION: return "fraction";
        case Lenmode::PIXELS: return "pixels";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Marker::Colorbar::to_string(Orientation e) {
    switch(e) {
        case Orientation::H: return "h";
        case Orientation::V: return "v";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Marker::Colorbar::to_string(Showexponent e) {
    switch(e) {
        case Showexponent::ALL: return "all";
        case Showexponent::FIRST: return "first";
        case Showexponent::LAST: return "last";
        case Showexponent::NONE: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Marker::Colorbar::to_string(Showtickprefix e) {
    switch(e) {
        case Showtickprefix::ALL: return "all";
        case Showtickprefix::FIRST: return "first";
        case Showtickprefix::LAST: return "last";
        case Showtickprefix::NONE: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Marker::Colorbar::to_string(Showticksuffix e) {
    switch(e) {
        case Showticksuffix::ALL: return "all";
        case Showticksuffix::FIRST: return "first";
        case Showticksuffix::LAST: return "last";
        case Showticksuffix::NONE: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Marker::Colorbar::to_string(Thicknessmode e) {
    switch(e) {
        case Thicknessmode::FRACTION: return "fraction";
        case Thicknessmode::PIXELS: return "pixels";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Marker::Colorbar::to_string(Ticklabeloverflow e) {
    switch(e) {
        case Ticklabeloverflow::ALLOW: return "allow";
        case Ticklabeloverflow::HIDE_PAST_DIV: return "hide past div";
        case Ticklabeloverflow::HIDE_PAST_DOMAIN: return "hide past domain";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Marker::Colorbar::to_string(Ticklabelposition e) {
    switch(e) {
        case Ticklabelposition::OUTSIDE: return "outside";
        case Ticklabelposition::INSIDE: return "inside";
        case Ticklabelposition::OUTSIDE_TOP: return "outside top";
        case Ticklabelposition::INSIDE_TOP: return "inside top";
        case Ticklabelposition::OUTSIDE_LEFT: return "outside left";
        case Ticklabelposition::INSIDE_LEFT: return "inside left";
        case Ticklabelposition::OUTSIDE_RIGHT: return "outside right";
        case Ticklabelposition::INSIDE_RIGHT: return "inside right";
        case Ticklabelposition::OUTSIDE_BOTTOM: return "outside bottom";
        case Ticklabelposition::INSIDE_BOTTOM: return "inside bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Marker::Colorbar::to_string(Tickmode e) {
    switch(e) {
        case Tickmode::AUTO: return "auto";
        case Tickmode::LINEAR: return "linear";
        case Tickmode::ARRAY: return "array";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Marker::Colorbar::to_string(Ticks e) {
    switch(e) {
        case Ticks::OUTSIDE: return "outside";
        case Ticks::INSIDE: return "inside";
        case Ticks::EMPTY: return "";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Marker::Colorbar::to_string(Xanchor e) {
    switch(e) {
        case Xanchor::LEFT: return "left";
        case Xanchor::CENTER: return "center";
        case Xanchor::RIGHT: return "right";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Marker::Colorbar::to_string(Xref e) {
    switch(e) {
        case Xref::CONTAINER: return "container";
        case Xref::PAPER: return "paper";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Marker::Colorbar::to_string(Yanchor e) {
    switch(e) {
        case Yanchor::TOP: return "top";
        case Yanchor::MIDDLE: return "middle";
        case Yanchor::BOTTOM: return "bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Marker::Colorbar::to_string(Yref e) {
    switch(e) {
        case Yref::CONTAINER: return "container";
        case Yref::PAPER: return "paper";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::borderwidth(double f) {
    json["borderwidth"] = std::move(f);
    return *this;
}

template <typename T>
Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::dtick(T f) {
    json["dtick"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::exponentformat(enum Exponentformat f) {
    json["exponentformat"] = to_string(f);
    return *this;
}

template <typename T>
Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::labelalias(T f) {
    json["labelalias"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::len(double f) {
    json["len"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::lenmode(enum Lenmode f) {
    json["lenmode"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::minexponent(double f) {
    json["minexponent"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::nticks(int f) {
    json["nticks"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::orientation(enum Orientation f) {
    json["orientation"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::outlinecolor(std::string f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}
Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::outlinecolor(double f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::outlinewidth(double f) {
    json["outlinewidth"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::separatethousands(bool f) {
    json["separatethousands"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::showexponent(enum Showexponent f) {
    json["showexponent"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::showticklabels(bool f) {
    json["showticklabels"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::showtickprefix(enum Showtickprefix f) {
    json["showtickprefix"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::showticksuffix(enum Showticksuffix f) {
    json["showticksuffix"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::thickness(double f) {
    json["thickness"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::thicknessmode(enum Thicknessmode f) {
    json["thicknessmode"] = to_string(f);
    return *this;
}

template <typename T>
Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::tick0(T f) {
    json["tick0"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::tickangle(double f) {
    json["tickangle"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::tickcolor(std::string f) {
    json["tickcolor"] = std::move(f);
    return *this;
}
Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::tickcolor(double f) {
    json["tickcolor"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::tickfont(Tickfont f) {
    json["tickfont"] = std::move(f.json);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::tickformat(std::string f) {
    json["tickformat"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::tickformatstops(Tickformatstops f) {
    json["tickformatstops"] = std::move(f.json);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::ticklabeloverflow(enum Ticklabeloverflow f) {
    json["ticklabeloverflow"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::ticklabelposition(enum Ticklabelposition f) {
    json["ticklabelposition"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::ticklabelstep(int f) {
    json["ticklabelstep"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::ticklen(double f) {
    json["ticklen"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::tickmode(enum Tickmode f) {
    json["tickmode"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::tickprefix(std::string f) {
    json["tickprefix"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::ticks(enum Ticks f) {
    json["ticks"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::ticksuffix(std::string f) {
    json["ticksuffix"] = std::move(f);
    return *this;
}

template <typename T, typename>
Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::ticktext(std::vector<T> f) {
    json["ticktext"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::ticktextsrc(std::string f) {
    json["ticktextsrc"] = std::move(f);
    return *this;
}

template <typename T, typename>
Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::tickvals(std::vector<T> f) {
    json["tickvals"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::tickvalssrc(std::string f) {
    json["tickvalssrc"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::tickwidth(double f) {
    json["tickwidth"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::title(Title f) {
    json["title"] = std::move(f.json);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::x(double f) {
    json["x"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::xanchor(enum Xanchor f) {
    json["xanchor"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::xpad(double f) {
    json["xpad"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::xref(enum Xref f) {
    json["xref"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::y(double f) {
    json["y"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::yanchor(enum Yanchor f) {
    json["yanchor"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::ypad(double f) {
    json["ypad"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar& Scattermap::Marker::Colorbar::yref(enum Yref f) {
    json["yref"] = to_string(f);
    return *this;
}

std::string Scattermap::Marker::Colorbar::Tickfont::to_string(Style e) {
    switch(e) {
        case Style::NORMAL: return "normal";
        case Style::ITALIC: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Marker::Colorbar::Tickfont::to_string(Textcase e) {
    switch(e) {
        case Textcase::NORMAL: return "normal";
        case Textcase::WORD_CAPS: return "word caps";
        case Textcase::UPPER: return "upper";
        case Textcase::LOWER: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Marker::Colorbar::Tickfont::to_string(Variant e) {
    switch(e) {
        case Variant::NORMAL: return "normal";
        case Variant::SMALL_CAPS: return "small-caps";
        case Variant::ALL_SMALL_CAPS: return "all-small-caps";
        case Variant::ALL_PETITE_CAPS: return "all-petite-caps";
        case Variant::PETITE_CAPS: return "petite-caps";
        case Variant::UNICASE: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scattermap::Marker::Colorbar::Tickfont& Scattermap::Marker::Colorbar::Tickfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scattermap::Marker::Colorbar::Tickfont& Scattermap::Marker::Colorbar::Tickfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar::Tickfont& Scattermap::Marker::Colorbar::Tickfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar::Tickfont& Scattermap::Marker::Colorbar::Tickfont::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar::Tickfont& Scattermap::Marker::Colorbar::Tickfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar::Tickfont& Scattermap::Marker::Colorbar::Tickfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar::Tickfont& Scattermap::Marker::Colorbar::Tickfont::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar::Tickfont& Scattermap::Marker::Colorbar::Tickfont::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar::Tickfont& Scattermap::Marker::Colorbar::Tickfont::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar::Tickfont& Scattermap::Marker::Colorbar::Tickfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


Scattermap::Marker::Colorbar::Tickformatstops& Scattermap::Marker::Colorbar::Tickformatstops::tickformatstop(Tickformatstop f) {
    json["tickformatstop"] = std::move(f.json);
    return *this;
}


Scattermap::Marker::Colorbar::Tickformatstops::Tickformatstop& Scattermap::Marker::Colorbar::Tickformatstops::Tickformatstop::dtickrange(std::vector<std::string> f) {
    json["dtickrange"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar::Tickformatstops::Tickformatstop& Scattermap::Marker::Colorbar::Tickformatstops::Tickformatstop::enabled(bool f) {
    json["enabled"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar::Tickformatstops::Tickformatstop& Scattermap::Marker::Colorbar::Tickformatstops::Tickformatstop::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar::Tickformatstops::Tickformatstop& Scattermap::Marker::Colorbar::Tickformatstops::Tickformatstop::templateitemname(std::string f) {
    json["templateitemname"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar::Tickformatstops::Tickformatstop& Scattermap::Marker::Colorbar::Tickformatstops::Tickformatstop::value(std::string f) {
    json["value"] = std::move(f);
    return *this;
}

std::string Scattermap::Marker::Colorbar::Title::to_string(Side e) {
    switch(e) {
        case Side::RIGHT: return "right";
        case Side::TOP: return "top";
        case Side::BOTTOM: return "bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scattermap::Marker::Colorbar::Title& Scattermap::Marker::Colorbar::Title::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}

Scattermap::Marker::Colorbar::Title& Scattermap::Marker::Colorbar::Title::side(enum Side f) {
    json["side"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar::Title& Scattermap::Marker::Colorbar::Title::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

std::string Scattermap::Marker::Colorbar::Title::Font::to_string(Style e) {
    switch(e) {
        case Style::NORMAL: return "normal";
        case Style::ITALIC: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Marker::Colorbar::Title::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::NORMAL: return "normal";
        case Textcase::WORD_CAPS: return "word caps";
        case Textcase::UPPER: return "upper";
        case Textcase::LOWER: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Scattermap::Marker::Colorbar::Title::Font::to_string(Variant e) {
    switch(e) {
        case Variant::NORMAL: return "normal";
        case Variant::SMALL_CAPS: return "small-caps";
        case Variant::ALL_SMALL_CAPS: return "all-small-caps";
        case Variant::ALL_PETITE_CAPS: return "all-petite-caps";
        case Variant::PETITE_CAPS: return "petite-caps";
        case Variant::UNICASE: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scattermap::Marker::Colorbar::Title::Font& Scattermap::Marker::Colorbar::Title::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scattermap::Marker::Colorbar::Title::Font& Scattermap::Marker::Colorbar::Title::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar::Title::Font& Scattermap::Marker::Colorbar::Title::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar::Title::Font& Scattermap::Marker::Colorbar::Title::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar::Title::Font& Scattermap::Marker::Colorbar::Title::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar::Title::Font& Scattermap::Marker::Colorbar::Title::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

Scattermap::Marker::Colorbar::Title::Font& Scattermap::Marker::Colorbar::Title::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar::Title::Font& Scattermap::Marker::Colorbar::Title::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar::Title::Font& Scattermap::Marker::Colorbar::Title::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

Scattermap::Marker::Colorbar::Title::Font& Scattermap::Marker::Colorbar::Title::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


Scattermap::Selected& Scattermap::Selected::marker(Marker f) {
    json["marker"] = std::move(f.json);
    return *this;
}


Scattermap::Selected::Marker& Scattermap::Selected::Marker::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scattermap::Selected::Marker& Scattermap::Selected::Marker::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

Scattermap::Selected::Marker& Scattermap::Selected::Marker::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}

Scattermap::Selected::Marker& Scattermap::Selected::Marker::size(double f) {
    json["size"] = std::move(f);
    return *this;
}


Scattermap::Stream& Scattermap::Stream::maxpoints(double f) {
    json["maxpoints"] = std::move(f);
    return *this;
}

Scattermap::Stream& Scattermap::Stream::token(std::string f) {
    json["token"] = std::move(f);
    return *this;
}

std::string Scattermap::Textfont::to_string(Style e) {
    switch(e) {
        case Style::NORMAL: return "normal";
        case Style::ITALIC: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Scattermap::Textfont& Scattermap::Textfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scattermap::Textfont& Scattermap::Textfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

Scattermap::Textfont& Scattermap::Textfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

Scattermap::Textfont& Scattermap::Textfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

Scattermap::Textfont& Scattermap::Textfont::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

Scattermap::Textfont& Scattermap::Textfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


Scattermap::Unselected& Scattermap::Unselected::marker(Marker f) {
    json["marker"] = std::move(f.json);
    return *this;
}


Scattermap::Unselected::Marker& Scattermap::Unselected::Marker::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Scattermap::Unselected::Marker& Scattermap::Unselected::Marker::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

Scattermap::Unselected::Marker& Scattermap::Unselected::Marker::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}

Scattermap::Unselected::Marker& Scattermap::Unselected::Marker::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

} // namespace plotlypp

