// Copyright (c) 2025 Jimmy O'Rourke
// Licensed under and subject to the terms of the LICENSE file accompanying this distribution.
// Official repository: https://github.com/jimmyorourke/plotlypp

// Autogenerated by plotlypp/generator, from official Plotly sources.
// See https://plotly.com/graphing-libraries.
// Do not edit, changes may be overwritten!

#pragma once

namespace plotlypp {

std::string Streamtube::to_string(Visible e) {
    switch(e) {
        case Visible::TRUE: return "True";
        case Visible::FALSE: return "False";
        case Visible::LEGENDONLY: return "legendonly";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Streamtube& Streamtube::autocolorscale(bool f) {
    json["autocolorscale"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::cauto(bool f) {
    json["cauto"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::cmax(double f) {
    json["cmax"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::cmid(double f) {
    json["cmid"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::cmin(double f) {
    json["cmin"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::coloraxis(std::string f) {
    json["coloraxis"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::colorbar(class Colorbar f) {
    json["colorbar"] = std::move(f.json);
    return *this;
}

Streamtube& Streamtube::colorscale(std::string f) {
    json["colorscale"] = std::move(f);
    return *this;
}
Streamtube& Streamtube::colorscale(std::vector<std::pair<double, std::string>> f) {
    json["colorscale"] = std::move(f);
    return *this;
}

template <typename T, typename>
Streamtube& Streamtube::customdata(std::vector<T> f) {
    json["customdata"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::customdatasrc(std::string f) {
    json["customdatasrc"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::hoverinfo(std::string f) {
    json["hoverinfo"] = std::move(f);
    return *this;
}
Streamtube& Streamtube::hoverinfo(std::vector<std::string> f) {
    json["hoverinfo"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::hoverinfosrc(std::string f) {
    json["hoverinfosrc"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::hoverlabel(class Hoverlabel f) {
    json["hoverlabel"] = std::move(f.json);
    return *this;
}

Streamtube& Streamtube::hovertemplate(std::string f) {
    json["hovertemplate"] = std::move(f);
    return *this;
}
Streamtube& Streamtube::hovertemplate(std::vector<std::string> f) {
    json["hovertemplate"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::hovertemplatesrc(std::string f) {
    json["hovertemplatesrc"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::hovertext(std::string f) {
    json["hovertext"] = std::move(f);
    return *this;
}

template <typename T, typename>
Streamtube& Streamtube::ids(std::vector<T> f) {
    json["ids"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::idssrc(std::string f) {
    json["idssrc"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::legend(std::string f) {
    json["legend"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::legendgroup(std::string f) {
    json["legendgroup"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::legendgrouptitle(class Legendgrouptitle f) {
    json["legendgrouptitle"] = std::move(f.json);
    return *this;
}

Streamtube& Streamtube::legendrank(double f) {
    json["legendrank"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::legendwidth(double f) {
    json["legendwidth"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::lighting(class Lighting f) {
    json["lighting"] = std::move(f.json);
    return *this;
}

Streamtube& Streamtube::lightposition(class Lightposition f) {
    json["lightposition"] = std::move(f.json);
    return *this;
}

Streamtube& Streamtube::maxdisplayed(int f) {
    json["maxdisplayed"] = std::move(f);
    return *this;
}

template <typename T>
Streamtube& Streamtube::meta(T f) {
    json["meta"] = std::move(f);
    return *this;
}
template <typename T>
Streamtube& Streamtube::meta(std::vector<T> f) {
    json["meta"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::metasrc(std::string f) {
    json["metasrc"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::reversescale(bool f) {
    json["reversescale"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::scene(std::string f) {
    json["scene"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::showlegend(bool f) {
    json["showlegend"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::showscale(bool f) {
    json["showscale"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::sizeref(double f) {
    json["sizeref"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::starts(class Starts f) {
    json["starts"] = std::move(f.json);
    return *this;
}

Streamtube& Streamtube::stream(class Stream f) {
    json["stream"] = std::move(f.json);
    return *this;
}

Streamtube& Streamtube::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

template <typename T, typename>
Streamtube& Streamtube::u(std::vector<T> f) {
    json["u"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::uhoverformat(std::string f) {
    json["uhoverformat"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::uid(std::string f) {
    json["uid"] = std::move(f);
    return *this;
}

template <typename T>
Streamtube& Streamtube::uirevision(T f) {
    json["uirevision"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::usrc(std::string f) {
    json["usrc"] = std::move(f);
    return *this;
}

template <typename T, typename>
Streamtube& Streamtube::v(std::vector<T> f) {
    json["v"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::vhoverformat(std::string f) {
    json["vhoverformat"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::visible(enum Visible f) {
    json["visible"] = to_string(f);
    return *this;
}

Streamtube& Streamtube::vsrc(std::string f) {
    json["vsrc"] = std::move(f);
    return *this;
}

template <typename T, typename>
Streamtube& Streamtube::w(std::vector<T> f) {
    json["w"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::whoverformat(std::string f) {
    json["whoverformat"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::wsrc(std::string f) {
    json["wsrc"] = std::move(f);
    return *this;
}

template <typename T, typename>
Streamtube& Streamtube::x(std::vector<T> f) {
    json["x"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::xhoverformat(std::string f) {
    json["xhoverformat"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::xsrc(std::string f) {
    json["xsrc"] = std::move(f);
    return *this;
}

template <typename T, typename>
Streamtube& Streamtube::y(std::vector<T> f) {
    json["y"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::yhoverformat(std::string f) {
    json["yhoverformat"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::ysrc(std::string f) {
    json["ysrc"] = std::move(f);
    return *this;
}

template <typename T, typename>
Streamtube& Streamtube::z(std::vector<T> f) {
    json["z"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::zhoverformat(std::string f) {
    json["zhoverformat"] = std::move(f);
    return *this;
}

Streamtube& Streamtube::zsrc(std::string f) {
    json["zsrc"] = std::move(f);
    return *this;
}

std::string Streamtube::Colorbar::to_string(Exponentformat e) {
    switch(e) {
        case Exponentformat::NONE: return "none";
        case Exponentformat::E: return "E";
        case Exponentformat::POWER: return "power";
        case Exponentformat::SI: return "SI";
        case Exponentformat::B: return "B";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Colorbar::to_string(Lenmode e) {
    switch(e) {
        case Lenmode::FRACTION: return "fraction";
        case Lenmode::PIXELS: return "pixels";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Colorbar::to_string(Orientation e) {
    switch(e) {
        case Orientation::H: return "h";
        case Orientation::V: return "v";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Colorbar::to_string(Showexponent e) {
    switch(e) {
        case Showexponent::ALL: return "all";
        case Showexponent::FIRST: return "first";
        case Showexponent::LAST: return "last";
        case Showexponent::NONE: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Colorbar::to_string(Showtickprefix e) {
    switch(e) {
        case Showtickprefix::ALL: return "all";
        case Showtickprefix::FIRST: return "first";
        case Showtickprefix::LAST: return "last";
        case Showtickprefix::NONE: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Colorbar::to_string(Showticksuffix e) {
    switch(e) {
        case Showticksuffix::ALL: return "all";
        case Showticksuffix::FIRST: return "first";
        case Showticksuffix::LAST: return "last";
        case Showticksuffix::NONE: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Colorbar::to_string(Thicknessmode e) {
    switch(e) {
        case Thicknessmode::FRACTION: return "fraction";
        case Thicknessmode::PIXELS: return "pixels";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Colorbar::to_string(Ticklabeloverflow e) {
    switch(e) {
        case Ticklabeloverflow::ALLOW: return "allow";
        case Ticklabeloverflow::HIDE_PAST_DIV: return "hide past div";
        case Ticklabeloverflow::HIDE_PAST_DOMAIN: return "hide past domain";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Colorbar::to_string(Ticklabelposition e) {
    switch(e) {
        case Ticklabelposition::OUTSIDE: return "outside";
        case Ticklabelposition::INSIDE: return "inside";
        case Ticklabelposition::OUTSIDE_TOP: return "outside top";
        case Ticklabelposition::INSIDE_TOP: return "inside top";
        case Ticklabelposition::OUTSIDE_LEFT: return "outside left";
        case Ticklabelposition::INSIDE_LEFT: return "inside left";
        case Ticklabelposition::OUTSIDE_RIGHT: return "outside right";
        case Ticklabelposition::INSIDE_RIGHT: return "inside right";
        case Ticklabelposition::OUTSIDE_BOTTOM: return "outside bottom";
        case Ticklabelposition::INSIDE_BOTTOM: return "inside bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Colorbar::to_string(Tickmode e) {
    switch(e) {
        case Tickmode::AUTO: return "auto";
        case Tickmode::LINEAR: return "linear";
        case Tickmode::ARRAY: return "array";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Colorbar::to_string(Ticks e) {
    switch(e) {
        case Ticks::OUTSIDE: return "outside";
        case Ticks::INSIDE: return "inside";
        case Ticks::EMPTY: return "";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Colorbar::to_string(Xanchor e) {
    switch(e) {
        case Xanchor::LEFT: return "left";
        case Xanchor::CENTER: return "center";
        case Xanchor::RIGHT: return "right";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Colorbar::to_string(Xref e) {
    switch(e) {
        case Xref::CONTAINER: return "container";
        case Xref::PAPER: return "paper";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Colorbar::to_string(Yanchor e) {
    switch(e) {
        case Yanchor::TOP: return "top";
        case Yanchor::MIDDLE: return "middle";
        case Yanchor::BOTTOM: return "bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Colorbar::to_string(Yref e) {
    switch(e) {
        case Yref::CONTAINER: return "container";
        case Yref::PAPER: return "paper";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Streamtube::Colorbar& Streamtube::Colorbar::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
Streamtube::Colorbar& Streamtube::Colorbar::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
Streamtube::Colorbar& Streamtube::Colorbar::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::borderwidth(double f) {
    json["borderwidth"] = std::move(f);
    return *this;
}

template <typename T>
Streamtube::Colorbar& Streamtube::Colorbar::dtick(T f) {
    json["dtick"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::exponentformat(enum Exponentformat f) {
    json["exponentformat"] = to_string(f);
    return *this;
}

template <typename T>
Streamtube::Colorbar& Streamtube::Colorbar::labelalias(T f) {
    json["labelalias"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::len(double f) {
    json["len"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::lenmode(enum Lenmode f) {
    json["lenmode"] = to_string(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::minexponent(double f) {
    json["minexponent"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::nticks(int f) {
    json["nticks"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::orientation(enum Orientation f) {
    json["orientation"] = to_string(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::outlinecolor(std::string f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}
Streamtube::Colorbar& Streamtube::Colorbar::outlinecolor(double f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::outlinewidth(double f) {
    json["outlinewidth"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::separatethousands(bool f) {
    json["separatethousands"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::showexponent(enum Showexponent f) {
    json["showexponent"] = to_string(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::showticklabels(bool f) {
    json["showticklabels"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::showtickprefix(enum Showtickprefix f) {
    json["showtickprefix"] = to_string(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::showticksuffix(enum Showticksuffix f) {
    json["showticksuffix"] = to_string(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::thickness(double f) {
    json["thickness"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::thicknessmode(enum Thicknessmode f) {
    json["thicknessmode"] = to_string(f);
    return *this;
}

template <typename T>
Streamtube::Colorbar& Streamtube::Colorbar::tick0(T f) {
    json["tick0"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::tickangle(double f) {
    json["tickangle"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::tickcolor(std::string f) {
    json["tickcolor"] = std::move(f);
    return *this;
}
Streamtube::Colorbar& Streamtube::Colorbar::tickcolor(double f) {
    json["tickcolor"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::tickfont(class Tickfont f) {
    json["tickfont"] = std::move(f.json);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::tickformat(std::string f) {
    json["tickformat"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::tickformatstops(class Tickformatstops f) {
    json["tickformatstops"] = std::move(f.json);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::ticklabeloverflow(enum Ticklabeloverflow f) {
    json["ticklabeloverflow"] = to_string(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::ticklabelposition(enum Ticklabelposition f) {
    json["ticklabelposition"] = to_string(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::ticklabelstep(int f) {
    json["ticklabelstep"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::ticklen(double f) {
    json["ticklen"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::tickmode(enum Tickmode f) {
    json["tickmode"] = to_string(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::tickprefix(std::string f) {
    json["tickprefix"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::ticks(enum Ticks f) {
    json["ticks"] = to_string(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::ticksuffix(std::string f) {
    json["ticksuffix"] = std::move(f);
    return *this;
}

template <typename T, typename>
Streamtube::Colorbar& Streamtube::Colorbar::ticktext(std::vector<T> f) {
    json["ticktext"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::ticktextsrc(std::string f) {
    json["ticktextsrc"] = std::move(f);
    return *this;
}

template <typename T, typename>
Streamtube::Colorbar& Streamtube::Colorbar::tickvals(std::vector<T> f) {
    json["tickvals"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::tickvalssrc(std::string f) {
    json["tickvalssrc"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::tickwidth(double f) {
    json["tickwidth"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::title(class Title f) {
    json["title"] = std::move(f.json);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::x(double f) {
    json["x"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::xanchor(enum Xanchor f) {
    json["xanchor"] = to_string(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::xpad(double f) {
    json["xpad"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::xref(enum Xref f) {
    json["xref"] = to_string(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::y(double f) {
    json["y"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::yanchor(enum Yanchor f) {
    json["yanchor"] = to_string(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::ypad(double f) {
    json["ypad"] = std::move(f);
    return *this;
}

Streamtube::Colorbar& Streamtube::Colorbar::yref(enum Yref f) {
    json["yref"] = to_string(f);
    return *this;
}

std::string Streamtube::Colorbar::Tickfont::to_string(Style e) {
    switch(e) {
        case Style::NORMAL: return "normal";
        case Style::ITALIC: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Colorbar::Tickfont::to_string(Textcase e) {
    switch(e) {
        case Textcase::NORMAL: return "normal";
        case Textcase::WORD_CAPS: return "word caps";
        case Textcase::UPPER: return "upper";
        case Textcase::LOWER: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Colorbar::Tickfont::to_string(Variant e) {
    switch(e) {
        case Variant::NORMAL: return "normal";
        case Variant::SMALL_CAPS: return "small-caps";
        case Variant::ALL_SMALL_CAPS: return "all-small-caps";
        case Variant::ALL_PETITE_CAPS: return "all-petite-caps";
        case Variant::PETITE_CAPS: return "petite-caps";
        case Variant::UNICASE: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Streamtube::Colorbar::Tickfont& Streamtube::Colorbar::Tickfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Streamtube::Colorbar::Tickfont& Streamtube::Colorbar::Tickfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

Streamtube::Colorbar::Tickfont& Streamtube::Colorbar::Tickfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

Streamtube::Colorbar::Tickfont& Streamtube::Colorbar::Tickfont::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

Streamtube::Colorbar::Tickfont& Streamtube::Colorbar::Tickfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

Streamtube::Colorbar::Tickfont& Streamtube::Colorbar::Tickfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

Streamtube::Colorbar::Tickfont& Streamtube::Colorbar::Tickfont::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

Streamtube::Colorbar::Tickfont& Streamtube::Colorbar::Tickfont::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

Streamtube::Colorbar::Tickfont& Streamtube::Colorbar::Tickfont::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

Streamtube::Colorbar::Tickfont& Streamtube::Colorbar::Tickfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


Streamtube::Colorbar::Tickformatstops& Streamtube::Colorbar::Tickformatstops::tickformatstop(class Tickformatstop f) {
    json["tickformatstop"] = std::move(f.json);
    return *this;
}


Streamtube::Colorbar::Tickformatstops::Tickformatstop& Streamtube::Colorbar::Tickformatstops::Tickformatstop::dtickrange(std::vector<std::string> f) {
    json["dtickrange"] = std::move(f);
    return *this;
}

Streamtube::Colorbar::Tickformatstops::Tickformatstop& Streamtube::Colorbar::Tickformatstops::Tickformatstop::enabled(bool f) {
    json["enabled"] = std::move(f);
    return *this;
}

Streamtube::Colorbar::Tickformatstops::Tickformatstop& Streamtube::Colorbar::Tickformatstops::Tickformatstop::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

Streamtube::Colorbar::Tickformatstops::Tickformatstop& Streamtube::Colorbar::Tickformatstops::Tickformatstop::templateitemname(std::string f) {
    json["templateitemname"] = std::move(f);
    return *this;
}

Streamtube::Colorbar::Tickformatstops::Tickformatstop& Streamtube::Colorbar::Tickformatstops::Tickformatstop::value(std::string f) {
    json["value"] = std::move(f);
    return *this;
}

std::string Streamtube::Colorbar::Title::to_string(Side e) {
    switch(e) {
        case Side::RIGHT: return "right";
        case Side::TOP: return "top";
        case Side::BOTTOM: return "bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Streamtube::Colorbar::Title& Streamtube::Colorbar::Title::font(class Font f) {
    json["font"] = std::move(f.json);
    return *this;
}

Streamtube::Colorbar::Title& Streamtube::Colorbar::Title::side(enum Side f) {
    json["side"] = to_string(f);
    return *this;
}

Streamtube::Colorbar::Title& Streamtube::Colorbar::Title::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

std::string Streamtube::Colorbar::Title::Font::to_string(Style e) {
    switch(e) {
        case Style::NORMAL: return "normal";
        case Style::ITALIC: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Colorbar::Title::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::NORMAL: return "normal";
        case Textcase::WORD_CAPS: return "word caps";
        case Textcase::UPPER: return "upper";
        case Textcase::LOWER: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Colorbar::Title::Font::to_string(Variant e) {
    switch(e) {
        case Variant::NORMAL: return "normal";
        case Variant::SMALL_CAPS: return "small-caps";
        case Variant::ALL_SMALL_CAPS: return "all-small-caps";
        case Variant::ALL_PETITE_CAPS: return "all-petite-caps";
        case Variant::PETITE_CAPS: return "petite-caps";
        case Variant::UNICASE: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Streamtube::Colorbar::Title::Font& Streamtube::Colorbar::Title::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Streamtube::Colorbar::Title::Font& Streamtube::Colorbar::Title::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

Streamtube::Colorbar::Title::Font& Streamtube::Colorbar::Title::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

Streamtube::Colorbar::Title::Font& Streamtube::Colorbar::Title::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

Streamtube::Colorbar::Title::Font& Streamtube::Colorbar::Title::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

Streamtube::Colorbar::Title::Font& Streamtube::Colorbar::Title::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

Streamtube::Colorbar::Title::Font& Streamtube::Colorbar::Title::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

Streamtube::Colorbar::Title::Font& Streamtube::Colorbar::Title::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

Streamtube::Colorbar::Title::Font& Streamtube::Colorbar::Title::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

Streamtube::Colorbar::Title::Font& Streamtube::Colorbar::Title::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}

std::string Streamtube::Hoverlabel::to_string(Align e) {
    switch(e) {
        case Align::LEFT: return "left";
        case Align::RIGHT: return "right";
        case Align::AUTO: return "auto";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Streamtube::Hoverlabel& Streamtube::Hoverlabel::align(enum Align f) {
    json["align"] = to_string(f);
    return *this;
}
Streamtube::Hoverlabel& Streamtube::Hoverlabel::align(const std::vector<enum Align>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["align"] = std::move(stringified);
    return *this;
}

Streamtube::Hoverlabel& Streamtube::Hoverlabel::alignsrc(std::string f) {
    json["alignsrc"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel& Streamtube::Hoverlabel::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
Streamtube::Hoverlabel& Streamtube::Hoverlabel::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
Streamtube::Hoverlabel& Streamtube::Hoverlabel::bgcolor(std::vector<std::string> f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
Streamtube::Hoverlabel& Streamtube::Hoverlabel::bgcolor(std::vector<double> f) {
    json["bgcolor"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel& Streamtube::Hoverlabel::bgcolorsrc(std::string f) {
    json["bgcolorsrc"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel& Streamtube::Hoverlabel::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
Streamtube::Hoverlabel& Streamtube::Hoverlabel::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
Streamtube::Hoverlabel& Streamtube::Hoverlabel::bordercolor(std::vector<std::string> f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
Streamtube::Hoverlabel& Streamtube::Hoverlabel::bordercolor(std::vector<double> f) {
    json["bordercolor"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel& Streamtube::Hoverlabel::bordercolorsrc(std::string f) {
    json["bordercolorsrc"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel& Streamtube::Hoverlabel::font(class Font f) {
    json["font"] = std::move(f.json);
    return *this;
}

Streamtube::Hoverlabel& Streamtube::Hoverlabel::namelength(int f) {
    json["namelength"] = std::move(f);
    return *this;
}
Streamtube::Hoverlabel& Streamtube::Hoverlabel::namelength(std::vector<int> f) {
    json["namelength"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel& Streamtube::Hoverlabel::namelengthsrc(std::string f) {
    json["namelengthsrc"] = std::move(f);
    return *this;
}

std::string Streamtube::Hoverlabel::Font::to_string(Style e) {
    switch(e) {
        case Style::NORMAL: return "normal";
        case Style::ITALIC: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Hoverlabel::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::NORMAL: return "normal";
        case Textcase::WORD_CAPS: return "word caps";
        case Textcase::UPPER: return "upper";
        case Textcase::LOWER: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Hoverlabel::Font::to_string(Variant e) {
    switch(e) {
        case Variant::NORMAL: return "normal";
        case Variant::SMALL_CAPS: return "small-caps";
        case Variant::ALL_SMALL_CAPS: return "all-small-caps";
        case Variant::ALL_PETITE_CAPS: return "all-petite-caps";
        case Variant::PETITE_CAPS: return "petite-caps";
        case Variant::UNICASE: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::color(std::vector<std::string> f) {
    json["color"] = std::move(f);
    return *this;
}
Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::color(std::vector<double> f) {
    json["color"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::family(std::vector<std::string> f) {
    json["family"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}
Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::lineposition(std::vector<std::string> f) {
    json["lineposition"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::linepositionsrc(std::string f) {
    json["linepositionsrc"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}
Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::shadow(std::vector<std::string> f) {
    json["shadow"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::shadowsrc(std::string f) {
    json["shadowsrc"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::size(std::vector<double> f) {
    json["size"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}
Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::style(const std::vector<enum Style>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["style"] = std::move(stringified);
    return *this;
}

Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}
Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::textcase(const std::vector<enum Textcase>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["textcase"] = std::move(stringified);
    return *this;
}

Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::textcasesrc(std::string f) {
    json["textcasesrc"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}
Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::variant(const std::vector<enum Variant>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["variant"] = std::move(stringified);
    return *this;
}

Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::weight(std::vector<int> f) {
    json["weight"] = std::move(f);
    return *this;
}

Streamtube::Hoverlabel::Font& Streamtube::Hoverlabel::Font::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}


Streamtube::Legendgrouptitle& Streamtube::Legendgrouptitle::font(class Font f) {
    json["font"] = std::move(f.json);
    return *this;
}

Streamtube::Legendgrouptitle& Streamtube::Legendgrouptitle::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

std::string Streamtube::Legendgrouptitle::Font::to_string(Style e) {
    switch(e) {
        case Style::NORMAL: return "normal";
        case Style::ITALIC: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Legendgrouptitle::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::NORMAL: return "normal";
        case Textcase::WORD_CAPS: return "word caps";
        case Textcase::UPPER: return "upper";
        case Textcase::LOWER: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
std::string Streamtube::Legendgrouptitle::Font::to_string(Variant e) {
    switch(e) {
        case Variant::NORMAL: return "normal";
        case Variant::SMALL_CAPS: return "small-caps";
        case Variant::ALL_SMALL_CAPS: return "all-small-caps";
        case Variant::ALL_PETITE_CAPS: return "all-petite-caps";
        case Variant::PETITE_CAPS: return "petite-caps";
        case Variant::UNICASE: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

Streamtube::Legendgrouptitle::Font& Streamtube::Legendgrouptitle::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
Streamtube::Legendgrouptitle::Font& Streamtube::Legendgrouptitle::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

Streamtube::Legendgrouptitle::Font& Streamtube::Legendgrouptitle::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

Streamtube::Legendgrouptitle::Font& Streamtube::Legendgrouptitle::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

Streamtube::Legendgrouptitle::Font& Streamtube::Legendgrouptitle::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

Streamtube::Legendgrouptitle::Font& Streamtube::Legendgrouptitle::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

Streamtube::Legendgrouptitle::Font& Streamtube::Legendgrouptitle::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

Streamtube::Legendgrouptitle::Font& Streamtube::Legendgrouptitle::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

Streamtube::Legendgrouptitle::Font& Streamtube::Legendgrouptitle::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

Streamtube::Legendgrouptitle::Font& Streamtube::Legendgrouptitle::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


Streamtube::Lighting& Streamtube::Lighting::ambient(double f) {
    json["ambient"] = std::move(f);
    return *this;
}

Streamtube::Lighting& Streamtube::Lighting::diffuse(double f) {
    json["diffuse"] = std::move(f);
    return *this;
}

Streamtube::Lighting& Streamtube::Lighting::facenormalsepsilon(double f) {
    json["facenormalsepsilon"] = std::move(f);
    return *this;
}

Streamtube::Lighting& Streamtube::Lighting::fresnel(double f) {
    json["fresnel"] = std::move(f);
    return *this;
}

Streamtube::Lighting& Streamtube::Lighting::roughness(double f) {
    json["roughness"] = std::move(f);
    return *this;
}

Streamtube::Lighting& Streamtube::Lighting::specular(double f) {
    json["specular"] = std::move(f);
    return *this;
}

Streamtube::Lighting& Streamtube::Lighting::vertexnormalsepsilon(double f) {
    json["vertexnormalsepsilon"] = std::move(f);
    return *this;
}


Streamtube::Lightposition& Streamtube::Lightposition::x(double f) {
    json["x"] = std::move(f);
    return *this;
}

Streamtube::Lightposition& Streamtube::Lightposition::y(double f) {
    json["y"] = std::move(f);
    return *this;
}

Streamtube::Lightposition& Streamtube::Lightposition::z(double f) {
    json["z"] = std::move(f);
    return *this;
}


template <typename T, typename>
Streamtube::Starts& Streamtube::Starts::x(std::vector<T> f) {
    json["x"] = std::move(f);
    return *this;
}

Streamtube::Starts& Streamtube::Starts::xsrc(std::string f) {
    json["xsrc"] = std::move(f);
    return *this;
}

template <typename T, typename>
Streamtube::Starts& Streamtube::Starts::y(std::vector<T> f) {
    json["y"] = std::move(f);
    return *this;
}

Streamtube::Starts& Streamtube::Starts::ysrc(std::string f) {
    json["ysrc"] = std::move(f);
    return *this;
}

template <typename T, typename>
Streamtube::Starts& Streamtube::Starts::z(std::vector<T> f) {
    json["z"] = std::move(f);
    return *this;
}

Streamtube::Starts& Streamtube::Starts::zsrc(std::string f) {
    json["zsrc"] = std::move(f);
    return *this;
}


Streamtube::Stream& Streamtube::Stream::maxpoints(double f) {
    json["maxpoints"] = std::move(f);
    return *this;
}

Streamtube::Stream& Streamtube::Stream::token(std::string f) {
    json["token"] = std::move(f);
    return *this;
}

} // namespace plotlypp

