// Copyright (c) 2025 Jimmy O'Rourke
// Licensed under and subject to the terms of the LICENSE file accompanying this distribution.
// Official repository: https://github.com/jimmyorourke/plotlypp

// Autogenerated by plotlypp/generator, from official Plotly sources.
// See https://plotly.com/graphing-libraries.
// Do not edit, changes may be overwritten!

#pragma once

#include <string>
#include <type_traits>
#include <vector>

#include <plotlypp/trace.hpp>
#include <plotlypp/traits.hpp>

#include <plotlypp/json.hpp>

namespace plotlypp {

class Sankey : public Trace {
 public:
    Sankey()
    : Trace() {
        json["type"] = "sankey";
    }

    enum class Arrangement {
        SNAP,
        PERPENDICULAR,
        FREEFORM,
        FIXED,
    };
    static std::string to_string(Arrangement e);

    enum class Orientation {
        V,
        H,
    };
    static std::string to_string(Orientation e);

    enum class Visible {
        TRUE,
        FALSE,
        LEGENDONLY,
    };
    static std::string to_string(Visible e);

    class Domain;
    class Hoverlabel;
    class Legendgrouptitle;
    // The links of the Sankey plot.
    class Link;
    // The nodes of the Sankey plot.
    class Node;
    class Stream;
    // Sets the font for node labels
    class Textfont;

    // If value is `snap` (the default), the node arrangement is assisted by automatic snapping of elements to preserve
    // space between nodes specified via `nodepad`. If value is `perpendicular`, the nodes can only move along a line
    // perpendicular to the flow. If value is `freeform`, the nodes can freely move on the plane. If value is `fixed`,
    // the nodes are stationary.
    // - Default: snap
    Sankey& arrangement(enum Arrangement f);

    // Assigns extra data each datum. This may be useful when listening to hover, click and selection events. Note that,
    // *scatter* traces also appends customdata items in the markers DOM elements
    template <typename T, typename = std::enable_if_t<is_data_array_element_v<T>>>
    Sankey& customdata(std::vector<T> f);

    // Sets the source reference on Chart Studio Cloud for `customdata`.
    Sankey& customdatasrc(std::string f);

    Sankey& domain(Domain f);

    // Determines which trace information appear on hover. If `none` or `skip` are set, no information is displayed upon
    // hovering. But, if `none` is set, click and hover events are still fired. Note that this attribute is superseded
    // by `node.hoverinfo` and `node.hoverinfo` for nodes and links respectively.
    // - Default: all
    // - Flags: []
    // - Extras ['all', 'none', 'skip']
    Sankey& hoverinfo(std::string f);

    Sankey& hoverlabel(Hoverlabel f);

    // Assigns id labels to each datum. These ids for object constancy of data points during animation. Should be an
    // array of strings, not numbers or any other type.
    template <typename T, typename = std::enable_if_t<is_data_array_element_v<T>>>
    Sankey& ids(std::vector<T> f);

    // Sets the source reference on Chart Studio Cloud for `ids`.
    Sankey& idssrc(std::string f);

    // Sets the reference to a legend to show this trace in. References to these legends are *legend*, *legend2*,
    // *legend3*, etc. Settings for these legends are set in the layout, under `layout.legend`, `layout.legend2`, etc.
    Sankey& legend(std::string f);

    Sankey& legendgrouptitle(Legendgrouptitle f);

    // Sets the legend rank for this trace. Items and groups with smaller ranks are presented on top/left side while
    // with *reversed* `legend.traceorder` they are on bottom/right side. The default legendrank is 1000, so that you
    // can use ranks less than 1000 to place certain items before all unranked items, and ranks greater than 1000 to go
    // after all unranked items. When having unranked or equal rank items shapes would be displayed after traces i.e.
    // according to their order in data and layout.
    Sankey& legendrank(double f);

    // Sets the width (in px or fraction) of the legend for this trace.
    Sankey& legendwidth(double f);

    // The links of the Sankey plot.
    Sankey& link(Link f);

    // Assigns extra meta information associated with this trace that can be used in various text attributes. Attributes
    // such as trace `name`, graph, axis and colorbar `title.text`, annotation `text` `rangeselector`, `updatemenues`
    // and `sliders` `label` text all support `meta`. To access the trace `meta` values in an attribute in the same
    // trace, simply use `%{meta[i]}` where `i` is the index or key of the `meta` item in question. To access trace
    // `meta` in layout attributes, use `%{data[n[.meta[i]}` where `i` is the index or key of the `meta` and `n` is the
    // trace index.
    template <typename T>
    Sankey& meta(T f);
    template <typename T>
    Sankey& meta(std::vector<T> f);

    // Sets the source reference on Chart Studio Cloud for `meta`.
    Sankey& metasrc(std::string f);

    // Sets the trace name. The trace name appears as the legend item and on hover.
    Sankey& name(std::string f);

    // The nodes of the Sankey plot.
    Sankey& node(Node f);

    // Sets the orientation of the Sankey diagram.
    // - Default: h
    Sankey& orientation(enum Orientation f);

    // Array containing integer indices of selected points. Has an effect only for traces that support selections. Note
    // that an empty array means an empty selection where the `unselected` are turned on for all points, whereas, any
    // other non-array values means no selection all where the `selected` and `unselected` styles have no effect.
    template <typename T>
    Sankey& selectedpoints(T f);

    Sankey& stream(Stream f);

    // Sets the font for node labels
    Sankey& textfont(Textfont f);

    // Assign an id to this trace, Use this to provide object constancy between traces during animations and
    // transitions.
    Sankey& uid(std::string f);

    // Controls persistence of some user-driven changes to the trace: `constraintrange` in `parcoords` traces, as well
    // as some `editable: true` modifications such as `name` and `colorbar.title`. Defaults to `layout.uirevision`. Note
    // that other user-driven trace attribute changes are controlled by `layout` attributes: `trace.visible` is
    // controlled by `layout.legend.uirevision`, `selectedpoints` is controlled by `layout.selectionrevision`, and
    // `colorbar.(x|y)` (accessible with `config: {editable: true}`) is controlled by `layout.editrevision`. Trace
    // changes are tracked by `uid`, which only falls back on trace index if no `uid` is provided. So if your app can
    // add/remove traces before the end of the `data` array, such that the same trace has a different index, you can
    // still preserve user-driven changes if you give each trace a `uid` that stays with it as it moves.
    template <typename T>
    Sankey& uirevision(T f);

    // Sets the value formatting rule using d3 formatting mini-languages which are very similar to those in Python. For
    // numbers, see: https://github.com/d3/d3-format/tree/v1.4.5#d3-format.
    Sankey& valueformat(std::string f);

    // Adds a unit to follow the value in the hover tooltip. Add a space if a separation is necessary from the value.
    Sankey& valuesuffix(std::string f);

    // Determines whether or not this trace is visible. If *legendonly*, the trace is not drawn, but can appear as a
    // legend item (provided that the legend itself is visible).
    // - Default: True
    Sankey& visible(enum Visible f);
};

class Sankey::Domain {
 public:

    // If there is a layout grid, use the domain for this column in the grid for this sankey trace .
    Sankey::Domain& column(int f);

    // If there is a layout grid, use the domain for this row in the grid for this sankey trace .
    Sankey::Domain& row(int f);

    // Sets the horizontal domain of this sankey trace (in plot fraction).
    Sankey::Domain& x(std::vector<std::string> f);

    // Sets the vertical domain of this sankey trace (in plot fraction).
    Sankey::Domain& y(std::vector<std::string> f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

class Sankey::Hoverlabel {
 public:

    enum class Align {
        LEFT,
        RIGHT,
        AUTO,
    };
    static std::string to_string(Align e);

    // Sets the font used in hover labels.
    class Font;

    // Sets the horizontal alignment of the text content within hover label box. Has an effect only if the hover label
    // text spans more two or more lines
    // - Default: auto
    Sankey::Hoverlabel& align(enum Align f);
    Sankey::Hoverlabel& align(const std::vector<enum Align>& f);

    // Sets the source reference on Chart Studio Cloud for `align`.
    Sankey::Hoverlabel& alignsrc(std::string f);

    // Sets the background color of the hover labels for this trace
    Sankey::Hoverlabel& bgcolor(std::string f);
    Sankey::Hoverlabel& bgcolor(double f);
    Sankey::Hoverlabel& bgcolor(std::vector<std::string> f);
    Sankey::Hoverlabel& bgcolor(std::vector<double> f);

    // Sets the source reference on Chart Studio Cloud for `bgcolor`.
    Sankey::Hoverlabel& bgcolorsrc(std::string f);

    // Sets the border color of the hover labels for this trace.
    Sankey::Hoverlabel& bordercolor(std::string f);
    Sankey::Hoverlabel& bordercolor(double f);
    Sankey::Hoverlabel& bordercolor(std::vector<std::string> f);
    Sankey::Hoverlabel& bordercolor(std::vector<double> f);

    // Sets the source reference on Chart Studio Cloud for `bordercolor`.
    Sankey::Hoverlabel& bordercolorsrc(std::string f);

    // Sets the font used in hover labels.
    Sankey::Hoverlabel& font(Font f);

    // Sets the default length (in number of characters) of the trace name in the hover labels for all traces. -1 shows
    // the whole name regardless of length. 0-3 shows the first 0-3 characters, and an integer >3 will show the whole
    // name if it is less than that many characters, but if it is longer, will truncate to `namelength - 3` characters
    // and add an ellipsis.
    Sankey::Hoverlabel& namelength(int f);
    Sankey::Hoverlabel& namelength(std::vector<int> f);

    // Sets the source reference on Chart Studio Cloud for `namelength`.
    Sankey::Hoverlabel& namelengthsrc(std::string f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

// Sets the font used in hover labels.
class Sankey::Hoverlabel::Font {
 public:

    enum class Style {
        NORMAL,
        ITALIC,
    };
    static std::string to_string(Style e);

    enum class Textcase {
        NORMAL,
        WORD_CAPS,
        UPPER,
        LOWER,
    };
    static std::string to_string(Textcase e);

    enum class Variant {
        NORMAL,
        SMALL_CAPS,
        ALL_SMALL_CAPS,
        ALL_PETITE_CAPS,
        PETITE_CAPS,
        UNICASE,
    };
    static std::string to_string(Variant e);

    Sankey::Hoverlabel::Font& color(std::string f);
    Sankey::Hoverlabel::Font& color(double f);
    Sankey::Hoverlabel::Font& color(std::vector<std::string> f);
    Sankey::Hoverlabel::Font& color(std::vector<double> f);

    // Sets the source reference on Chart Studio Cloud for `color`.
    Sankey::Hoverlabel::Font& colorsrc(std::string f);

    // HTML font family - the typeface that will be applied by the web browser. The web browser will only be able to
    // apply a font if it is available on the system which it operates. Provide multiple font families, separated by
    // commas, to indicate the preference in which to apply fonts if they aren't available on the system. The Chart
    // Studio Cloud (at https://chart-studio.plotly.com or on-premise) generates images on a server, where only a select
    // number of fonts are installed and supported. These include *Arial*, *Balto*, *Courier New*, *Droid Sans*, *Droid
    // Serif*, *Droid Sans Mono*, *Gravitas One*, *Old Standard TT*, *Open Sans*, *Overpass*, *PT Sans Narrow*,
    // *Raleway*, *Times New Roman*.
    Sankey::Hoverlabel::Font& family(std::string f);
    Sankey::Hoverlabel::Font& family(std::vector<std::string> f);

    // Sets the source reference on Chart Studio Cloud for `family`.
    Sankey::Hoverlabel::Font& familysrc(std::string f);

    // Sets the kind of decoration line(s) with text, such as an *under*, *over* or *through* as well as combinations
    // e.g. *under+over*, etc.
    // - Default: none
    // - Flags: ['under', 'over', 'through']
    // - Extras ['none']
    Sankey::Hoverlabel::Font& lineposition(std::string f);
    Sankey::Hoverlabel::Font& lineposition(std::vector<std::string> f);

    // Sets the source reference on Chart Studio Cloud for `lineposition`.
    Sankey::Hoverlabel::Font& linepositionsrc(std::string f);

    // Sets the shape and color of the shadow behind text. *auto* places minimal shadow and applies contrast text font
    // color. See https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow for additional options.
    Sankey::Hoverlabel::Font& shadow(std::string f);
    Sankey::Hoverlabel::Font& shadow(std::vector<std::string> f);

    // Sets the source reference on Chart Studio Cloud for `shadow`.
    Sankey::Hoverlabel::Font& shadowsrc(std::string f);

    Sankey::Hoverlabel::Font& size(double f);
    Sankey::Hoverlabel::Font& size(std::vector<double> f);

    // Sets the source reference on Chart Studio Cloud for `size`.
    Sankey::Hoverlabel::Font& sizesrc(std::string f);

    // Sets whether a font should be styled with a normal or italic face from its family.
    // - Default: normal
    Sankey::Hoverlabel::Font& style(enum Style f);
    Sankey::Hoverlabel::Font& style(const std::vector<enum Style>& f);

    // Sets the source reference on Chart Studio Cloud for `style`.
    Sankey::Hoverlabel::Font& stylesrc(std::string f);

    // Sets capitalization of text. It can be used to make text appear in all-uppercase or all-lowercase, or with each
    // word capitalized.
    // - Default: normal
    Sankey::Hoverlabel::Font& textcase(enum Textcase f);
    Sankey::Hoverlabel::Font& textcase(const std::vector<enum Textcase>& f);

    // Sets the source reference on Chart Studio Cloud for `textcase`.
    Sankey::Hoverlabel::Font& textcasesrc(std::string f);

    // Sets the variant of the font.
    // - Default: normal
    Sankey::Hoverlabel::Font& variant(enum Variant f);
    Sankey::Hoverlabel::Font& variant(const std::vector<enum Variant>& f);

    // Sets the source reference on Chart Studio Cloud for `variant`.
    Sankey::Hoverlabel::Font& variantsrc(std::string f);

    // Sets the weight (or boldness) of the font.
    Sankey::Hoverlabel::Font& weight(int f);
    Sankey::Hoverlabel::Font& weight(std::vector<int> f);

    // Sets the source reference on Chart Studio Cloud for `weight`.
    Sankey::Hoverlabel::Font& weightsrc(std::string f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

class Sankey::Legendgrouptitle {
 public:

    // Sets this legend group's title font.
    class Font;

    // Sets this legend group's title font.
    Sankey::Legendgrouptitle& font(Font f);

    // Sets the title of the legend group.
    Sankey::Legendgrouptitle& text(std::string f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

// Sets this legend group's title font.
class Sankey::Legendgrouptitle::Font {
 public:

    enum class Style {
        NORMAL,
        ITALIC,
    };
    static std::string to_string(Style e);

    enum class Textcase {
        NORMAL,
        WORD_CAPS,
        UPPER,
        LOWER,
    };
    static std::string to_string(Textcase e);

    enum class Variant {
        NORMAL,
        SMALL_CAPS,
        ALL_SMALL_CAPS,
        ALL_PETITE_CAPS,
        PETITE_CAPS,
        UNICASE,
    };
    static std::string to_string(Variant e);

    Sankey::Legendgrouptitle::Font& color(std::string f);
    Sankey::Legendgrouptitle::Font& color(double f);

    // HTML font family - the typeface that will be applied by the web browser. The web browser will only be able to
    // apply a font if it is available on the system which it operates. Provide multiple font families, separated by
    // commas, to indicate the preference in which to apply fonts if they aren't available on the system. The Chart
    // Studio Cloud (at https://chart-studio.plotly.com or on-premise) generates images on a server, where only a select
    // number of fonts are installed and supported. These include *Arial*, *Balto*, *Courier New*, *Droid Sans*, *Droid
    // Serif*, *Droid Sans Mono*, *Gravitas One*, *Old Standard TT*, *Open Sans*, *Overpass*, *PT Sans Narrow*,
    // *Raleway*, *Times New Roman*.
    Sankey::Legendgrouptitle::Font& family(std::string f);

    // Sets the kind of decoration line(s) with text, such as an *under*, *over* or *through* as well as combinations
    // e.g. *under+over*, etc.
    // - Default: none
    // - Flags: ['under', 'over', 'through']
    // - Extras ['none']
    Sankey::Legendgrouptitle::Font& lineposition(std::string f);

    // Sets the shape and color of the shadow behind text. *auto* places minimal shadow and applies contrast text font
    // color. See https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow for additional options.
    Sankey::Legendgrouptitle::Font& shadow(std::string f);

    Sankey::Legendgrouptitle::Font& size(double f);

    // Sets whether a font should be styled with a normal or italic face from its family.
    // - Default: normal
    Sankey::Legendgrouptitle::Font& style(enum Style f);

    // Sets capitalization of text. It can be used to make text appear in all-uppercase or all-lowercase, or with each
    // word capitalized.
    // - Default: normal
    Sankey::Legendgrouptitle::Font& textcase(enum Textcase f);

    // Sets the variant of the font.
    // - Default: normal
    Sankey::Legendgrouptitle::Font& variant(enum Variant f);

    // Sets the weight (or boldness) of the font.
    Sankey::Legendgrouptitle::Font& weight(int f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

// The links of the Sankey plot.
class Sankey::Link {
 public:

    enum class Hoverinfo {
        ALL,
        NONE,
        SKIP,
    };
    static std::string to_string(Hoverinfo e);

    class Colorscales;
    class Hoverlabel;
    class Line;

    // Sets the length (in px) of the links arrow, if 0 no arrow will be drawn.
    Sankey::Link& arrowlen(double f);

    // Sets the `link` color. It can be a single value, or an array for specifying color for each `link`. If
    // `link.color` is omitted, then by default, a translucent grey link will be used.
    Sankey::Link& color(std::string f);
    Sankey::Link& color(double f);
    Sankey::Link& color(std::vector<std::string> f);
    Sankey::Link& color(std::vector<double> f);

    Sankey::Link& colorscales(Colorscales f);

    // Sets the source reference on Chart Studio Cloud for `color`.
    Sankey::Link& colorsrc(std::string f);

    // Assigns extra data to each link.
    template <typename T, typename = std::enable_if_t<is_data_array_element_v<T>>>
    Sankey::Link& customdata(std::vector<T> f);

    // Sets the source reference on Chart Studio Cloud for `customdata`.
    Sankey::Link& customdatasrc(std::string f);

    // Sets the `link` hover color. It can be a single value, or an array for specifying hover colors for each `link`.
    // If `link.hovercolor` is omitted, then by default, links will become slightly more opaque when hovered over.
    Sankey::Link& hovercolor(std::string f);
    Sankey::Link& hovercolor(double f);
    Sankey::Link& hovercolor(std::vector<std::string> f);
    Sankey::Link& hovercolor(std::vector<double> f);

    // Sets the source reference on Chart Studio Cloud for `hovercolor`.
    Sankey::Link& hovercolorsrc(std::string f);

    // Determines which trace information appear when hovering links. If `none` or `skip` are set, no information is
    // displayed upon hovering. But, if `none` is set, click and hover events are still fired.
    // - Default: all
    Sankey::Link& hoverinfo(enum Hoverinfo f);

    Sankey::Link& hoverlabel(Hoverlabel f);

    // Template string used for rendering the information that appear on hover box. Note that this will override
    // `hoverinfo`. Variables are inserted using %{variable}, for example "y: %{y}" as well as %{xother}, {%_xother},
    // {%_xother_}, {%xother_}. When showing info for several points, *xother* will be added to those with different x
    // positions from the first point. An underscore before or after *(x|y)other* will add a space on that side, only
    // when this field is shown. Numbers are formatted using d3-format's syntax %{variable:d3-format}, for example
    // "Price: %{y:$.2f}". https://github.com/d3/d3-format/tree/v1.4.5#d3-format for details on the formatting syntax.
    // Dates are formatted using d3-time-format's syntax %{variable|d3-time-format}, for example "Day:
    // %{2019-01-01|%A}". https://github.com/d3/d3-time-format/tree/v2.2.3#locale_format for details on the date
    // formatting syntax. The variables available in `hovertemplate` are the ones emitted as event data described at
    // this link https://plotly.com/javascript/plotlyjs-events/#event-data. Additionally, every attributes that can be
    // specified per-point (the ones that are `arrayOk: true`) are available.  Variables `source` and `target` are node
    // objects.Finally, the template string has access to variables `value` and `label`. Anything contained in tag
    // `<extra>` is displayed in the secondary box, for example "<extra>{fullData.name}</extra>". To hide the secondary
    // box completely, use an empty tag `<extra></extra>`.
    Sankey::Link& hovertemplate(std::string f);
    Sankey::Link& hovertemplate(std::vector<std::string> f);

    // Sets the source reference on Chart Studio Cloud for `hovertemplate`.
    Sankey::Link& hovertemplatesrc(std::string f);

    // The shown name of the link.
    template <typename T, typename = std::enable_if_t<is_data_array_element_v<T>>>
    Sankey::Link& label(std::vector<T> f);

    // Sets the source reference on Chart Studio Cloud for `label`.
    Sankey::Link& labelsrc(std::string f);

    Sankey::Link& line(Line f);

    // An integer number `[0..nodes.length - 1]` that represents the source node.
    template <typename T, typename = std::enable_if_t<is_data_array_element_v<T>>>
    Sankey::Link& source(std::vector<T> f);

    // Sets the source reference on Chart Studio Cloud for `source`.
    Sankey::Link& sourcesrc(std::string f);

    // An integer number `[0..nodes.length - 1]` that represents the target node.
    template <typename T, typename = std::enable_if_t<is_data_array_element_v<T>>>
    Sankey::Link& target(std::vector<T> f);

    // Sets the source reference on Chart Studio Cloud for `target`.
    Sankey::Link& targetsrc(std::string f);

    // A numeric value representing the flow volume value.
    template <typename T, typename = std::enable_if_t<is_data_array_element_v<T>>>
    Sankey::Link& value(std::vector<T> f);

    // Sets the source reference on Chart Studio Cloud for `value`.
    Sankey::Link& valuesrc(std::string f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

class Sankey::Link::Colorscales {
 public:

    class Concentrationscales;

    Sankey::Link::Colorscales& concentrationscales(Concentrationscales f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

class Sankey::Link::Colorscales::Concentrationscales {
 public:

    // Sets the upper bound of the color domain.
    Sankey::Link::Colorscales::Concentrationscales& cmax(double f);

    // Sets the lower bound of the color domain.
    Sankey::Link::Colorscales::Concentrationscales& cmin(double f);

    // Sets the colorscale. The colorscale must be an array containing arrays mapping a normalized value to an rgb,
    // rgba, hex, hsl, hsv, or named color string. At minimum, a mapping for the lowest (0) and highest (1) values are
    // required. For example, `[[0, 'rgb(0,0,255)'], [1, 'rgb(255,0,0)']]`. To control the bounds of the colorscale in
    // color space, use `cmin` and `cmax`. Alternatively, `colorscale` may be a palette name string of the following
    // list:
    // Blackbody,Bluered,Blues,Cividis,Earth,Electric,Greens,Greys,Hot,Jet,Picnic,Portland,Rainbow,RdBu,Reds,Viridis,YlGnBu,YlOrRd.
    Sankey::Link::Colorscales::Concentrationscales& colorscale(std::string f);
    Sankey::Link::Colorscales::Concentrationscales& colorscale(std::vector<std::pair<double, std::string>> f);

    // The label of the links to color based on their concentration within a flow.
    Sankey::Link::Colorscales::Concentrationscales& label(std::string f);

    // When used in a template, named items are created in the output figure in addition to any items the figure already
    // has in this array. You can modify these items in the output figure by making your own item with
    // `templateitemname` matching this `name` alongside your modifications (including `visible: false` or `enabled:
    // false` to hide it). Has no effect outside of a template.
    Sankey::Link::Colorscales::Concentrationscales& name(std::string f);

    // Used to refer to a named item in this array in the template. Named items from the template will be created even
    // without a matching item in the input figure, but you can modify one by making an item with `templateitemname`
    // matching its `name`, alongside your modifications (including `visible: false` or `enabled: false` to hide it). If
    // there is no template or no matching item, this item will be hidden unless you explicitly show it with `visible:
    // true`.
    Sankey::Link::Colorscales::Concentrationscales& templateitemname(std::string f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

class Sankey::Link::Hoverlabel {
 public:

    enum class Align {
        LEFT,
        RIGHT,
        AUTO,
    };
    static std::string to_string(Align e);

    // Sets the font used in hover labels.
    class Font;

    // Sets the horizontal alignment of the text content within hover label box. Has an effect only if the hover label
    // text spans more two or more lines
    // - Default: auto
    Sankey::Link::Hoverlabel& align(enum Align f);
    Sankey::Link::Hoverlabel& align(const std::vector<enum Align>& f);

    // Sets the source reference on Chart Studio Cloud for `align`.
    Sankey::Link::Hoverlabel& alignsrc(std::string f);

    // Sets the background color of the hover labels for this trace
    Sankey::Link::Hoverlabel& bgcolor(std::string f);
    Sankey::Link::Hoverlabel& bgcolor(double f);
    Sankey::Link::Hoverlabel& bgcolor(std::vector<std::string> f);
    Sankey::Link::Hoverlabel& bgcolor(std::vector<double> f);

    // Sets the source reference on Chart Studio Cloud for `bgcolor`.
    Sankey::Link::Hoverlabel& bgcolorsrc(std::string f);

    // Sets the border color of the hover labels for this trace.
    Sankey::Link::Hoverlabel& bordercolor(std::string f);
    Sankey::Link::Hoverlabel& bordercolor(double f);
    Sankey::Link::Hoverlabel& bordercolor(std::vector<std::string> f);
    Sankey::Link::Hoverlabel& bordercolor(std::vector<double> f);

    // Sets the source reference on Chart Studio Cloud for `bordercolor`.
    Sankey::Link::Hoverlabel& bordercolorsrc(std::string f);

    // Sets the font used in hover labels.
    Sankey::Link::Hoverlabel& font(Font f);

    // Sets the default length (in number of characters) of the trace name in the hover labels for all traces. -1 shows
    // the whole name regardless of length. 0-3 shows the first 0-3 characters, and an integer >3 will show the whole
    // name if it is less than that many characters, but if it is longer, will truncate to `namelength - 3` characters
    // and add an ellipsis.
    Sankey::Link::Hoverlabel& namelength(int f);
    Sankey::Link::Hoverlabel& namelength(std::vector<int> f);

    // Sets the source reference on Chart Studio Cloud for `namelength`.
    Sankey::Link::Hoverlabel& namelengthsrc(std::string f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

// Sets the font used in hover labels.
class Sankey::Link::Hoverlabel::Font {
 public:

    enum class Style {
        NORMAL,
        ITALIC,
    };
    static std::string to_string(Style e);

    enum class Textcase {
        NORMAL,
        WORD_CAPS,
        UPPER,
        LOWER,
    };
    static std::string to_string(Textcase e);

    enum class Variant {
        NORMAL,
        SMALL_CAPS,
        ALL_SMALL_CAPS,
        ALL_PETITE_CAPS,
        PETITE_CAPS,
        UNICASE,
    };
    static std::string to_string(Variant e);

    Sankey::Link::Hoverlabel::Font& color(std::string f);
    Sankey::Link::Hoverlabel::Font& color(double f);
    Sankey::Link::Hoverlabel::Font& color(std::vector<std::string> f);
    Sankey::Link::Hoverlabel::Font& color(std::vector<double> f);

    // Sets the source reference on Chart Studio Cloud for `color`.
    Sankey::Link::Hoverlabel::Font& colorsrc(std::string f);

    // HTML font family - the typeface that will be applied by the web browser. The web browser will only be able to
    // apply a font if it is available on the system which it operates. Provide multiple font families, separated by
    // commas, to indicate the preference in which to apply fonts if they aren't available on the system. The Chart
    // Studio Cloud (at https://chart-studio.plotly.com or on-premise) generates images on a server, where only a select
    // number of fonts are installed and supported. These include *Arial*, *Balto*, *Courier New*, *Droid Sans*, *Droid
    // Serif*, *Droid Sans Mono*, *Gravitas One*, *Old Standard TT*, *Open Sans*, *Overpass*, *PT Sans Narrow*,
    // *Raleway*, *Times New Roman*.
    Sankey::Link::Hoverlabel::Font& family(std::string f);
    Sankey::Link::Hoverlabel::Font& family(std::vector<std::string> f);

    // Sets the source reference on Chart Studio Cloud for `family`.
    Sankey::Link::Hoverlabel::Font& familysrc(std::string f);

    // Sets the kind of decoration line(s) with text, such as an *under*, *over* or *through* as well as combinations
    // e.g. *under+over*, etc.
    // - Default: none
    // - Flags: ['under', 'over', 'through']
    // - Extras ['none']
    Sankey::Link::Hoverlabel::Font& lineposition(std::string f);
    Sankey::Link::Hoverlabel::Font& lineposition(std::vector<std::string> f);

    // Sets the source reference on Chart Studio Cloud for `lineposition`.
    Sankey::Link::Hoverlabel::Font& linepositionsrc(std::string f);

    // Sets the shape and color of the shadow behind text. *auto* places minimal shadow and applies contrast text font
    // color. See https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow for additional options.
    Sankey::Link::Hoverlabel::Font& shadow(std::string f);
    Sankey::Link::Hoverlabel::Font& shadow(std::vector<std::string> f);

    // Sets the source reference on Chart Studio Cloud for `shadow`.
    Sankey::Link::Hoverlabel::Font& shadowsrc(std::string f);

    Sankey::Link::Hoverlabel::Font& size(double f);
    Sankey::Link::Hoverlabel::Font& size(std::vector<double> f);

    // Sets the source reference on Chart Studio Cloud for `size`.
    Sankey::Link::Hoverlabel::Font& sizesrc(std::string f);

    // Sets whether a font should be styled with a normal or italic face from its family.
    // - Default: normal
    Sankey::Link::Hoverlabel::Font& style(enum Style f);
    Sankey::Link::Hoverlabel::Font& style(const std::vector<enum Style>& f);

    // Sets the source reference on Chart Studio Cloud for `style`.
    Sankey::Link::Hoverlabel::Font& stylesrc(std::string f);

    // Sets capitalization of text. It can be used to make text appear in all-uppercase or all-lowercase, or with each
    // word capitalized.
    // - Default: normal
    Sankey::Link::Hoverlabel::Font& textcase(enum Textcase f);
    Sankey::Link::Hoverlabel::Font& textcase(const std::vector<enum Textcase>& f);

    // Sets the source reference on Chart Studio Cloud for `textcase`.
    Sankey::Link::Hoverlabel::Font& textcasesrc(std::string f);

    // Sets the variant of the font.
    // - Default: normal
    Sankey::Link::Hoverlabel::Font& variant(enum Variant f);
    Sankey::Link::Hoverlabel::Font& variant(const std::vector<enum Variant>& f);

    // Sets the source reference on Chart Studio Cloud for `variant`.
    Sankey::Link::Hoverlabel::Font& variantsrc(std::string f);

    // Sets the weight (or boldness) of the font.
    Sankey::Link::Hoverlabel::Font& weight(int f);
    Sankey::Link::Hoverlabel::Font& weight(std::vector<int> f);

    // Sets the source reference on Chart Studio Cloud for `weight`.
    Sankey::Link::Hoverlabel::Font& weightsrc(std::string f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

class Sankey::Link::Line {
 public:

    // Sets the color of the `line` around each `link`.
    Sankey::Link::Line& color(std::string f);
    Sankey::Link::Line& color(double f);
    Sankey::Link::Line& color(std::vector<std::string> f);
    Sankey::Link::Line& color(std::vector<double> f);

    // Sets the source reference on Chart Studio Cloud for `color`.
    Sankey::Link::Line& colorsrc(std::string f);

    // Sets the width (in px) of the `line` around each `link`.
    Sankey::Link::Line& width(double f);
    Sankey::Link::Line& width(std::vector<double> f);

    // Sets the source reference on Chart Studio Cloud for `width`.
    Sankey::Link::Line& widthsrc(std::string f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

// The nodes of the Sankey plot.
class Sankey::Node {
 public:

    enum class Align {
        JUSTIFY,
        LEFT,
        RIGHT,
        CENTER,
    };
    static std::string to_string(Align e);

    enum class Hoverinfo {
        ALL,
        NONE,
        SKIP,
    };
    static std::string to_string(Hoverinfo e);

    class Hoverlabel;
    class Line;

    // Sets the alignment method used to position the nodes along the horizontal axis.
    // - Default: justify
    Sankey::Node& align(enum Align f);

    // Sets the `node` color. It can be a single value, or an array for specifying color for each `node`. If
    // `node.color` is omitted, then the default `Plotly` color palette will be cycled through to have a variety of
    // colors. These defaults are not fully opaque, to allow some visibility of what is beneath the node.
    Sankey::Node& color(std::string f);
    Sankey::Node& color(double f);
    Sankey::Node& color(std::vector<std::string> f);
    Sankey::Node& color(std::vector<double> f);

    // Sets the source reference on Chart Studio Cloud for `color`.
    Sankey::Node& colorsrc(std::string f);

    // Assigns extra data to each node.
    template <typename T, typename = std::enable_if_t<is_data_array_element_v<T>>>
    Sankey::Node& customdata(std::vector<T> f);

    // Sets the source reference on Chart Studio Cloud for `customdata`.
    Sankey::Node& customdatasrc(std::string f);

    // Groups of nodes. Each group is defined by an array with the indices of the nodes it contains. Multiple groups can
    // be specified.
    Sankey::Node& groups(std::vector<std::string> f);

    // Determines which trace information appear when hovering nodes. If `none` or `skip` are set, no information is
    // displayed upon hovering. But, if `none` is set, click and hover events are still fired.
    // - Default: all
    Sankey::Node& hoverinfo(enum Hoverinfo f);

    Sankey::Node& hoverlabel(Hoverlabel f);

    // Template string used for rendering the information that appear on hover box. Note that this will override
    // `hoverinfo`. Variables are inserted using %{variable}, for example "y: %{y}" as well as %{xother}, {%_xother},
    // {%_xother_}, {%xother_}. When showing info for several points, *xother* will be added to those with different x
    // positions from the first point. An underscore before or after *(x|y)other* will add a space on that side, only
    // when this field is shown. Numbers are formatted using d3-format's syntax %{variable:d3-format}, for example
    // "Price: %{y:$.2f}". https://github.com/d3/d3-format/tree/v1.4.5#d3-format for details on the formatting syntax.
    // Dates are formatted using d3-time-format's syntax %{variable|d3-time-format}, for example "Day:
    // %{2019-01-01|%A}". https://github.com/d3/d3-time-format/tree/v2.2.3#locale_format for details on the date
    // formatting syntax. The variables available in `hovertemplate` are the ones emitted as event data described at
    // this link https://plotly.com/javascript/plotlyjs-events/#event-data. Additionally, every attributes that can be
    // specified per-point (the ones that are `arrayOk: true`) are available.  Variables `sourceLinks` and `targetLinks`
    // are arrays of link objects.Finally, the template string has access to variables `value` and `label`. Anything
    // contained in tag `<extra>` is displayed in the secondary box, for example "<extra>{fullData.name}</extra>". To
    // hide the secondary box completely, use an empty tag `<extra></extra>`.
    Sankey::Node& hovertemplate(std::string f);
    Sankey::Node& hovertemplate(std::vector<std::string> f);

    // Sets the source reference on Chart Studio Cloud for `hovertemplate`.
    Sankey::Node& hovertemplatesrc(std::string f);

    // The shown name of the node.
    template <typename T, typename = std::enable_if_t<is_data_array_element_v<T>>>
    Sankey::Node& label(std::vector<T> f);

    // Sets the source reference on Chart Studio Cloud for `label`.
    Sankey::Node& labelsrc(std::string f);

    Sankey::Node& line(Line f);

    // Sets the padding (in px) between the `nodes`.
    Sankey::Node& pad(double f);

    // Sets the thickness (in px) of the `nodes`.
    Sankey::Node& thickness(double f);

    // The normalized horizontal position of the node.
    template <typename T, typename = std::enable_if_t<is_data_array_element_v<T>>>
    Sankey::Node& x(std::vector<T> f);

    // Sets the source reference on Chart Studio Cloud for `x`.
    Sankey::Node& xsrc(std::string f);

    // The normalized vertical position of the node.
    template <typename T, typename = std::enable_if_t<is_data_array_element_v<T>>>
    Sankey::Node& y(std::vector<T> f);

    // Sets the source reference on Chart Studio Cloud for `y`.
    Sankey::Node& ysrc(std::string f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

class Sankey::Node::Hoverlabel {
 public:

    enum class Align {
        LEFT,
        RIGHT,
        AUTO,
    };
    static std::string to_string(Align e);

    // Sets the font used in hover labels.
    class Font;

    // Sets the horizontal alignment of the text content within hover label box. Has an effect only if the hover label
    // text spans more two or more lines
    // - Default: auto
    Sankey::Node::Hoverlabel& align(enum Align f);
    Sankey::Node::Hoverlabel& align(const std::vector<enum Align>& f);

    // Sets the source reference on Chart Studio Cloud for `align`.
    Sankey::Node::Hoverlabel& alignsrc(std::string f);

    // Sets the background color of the hover labels for this trace
    Sankey::Node::Hoverlabel& bgcolor(std::string f);
    Sankey::Node::Hoverlabel& bgcolor(double f);
    Sankey::Node::Hoverlabel& bgcolor(std::vector<std::string> f);
    Sankey::Node::Hoverlabel& bgcolor(std::vector<double> f);

    // Sets the source reference on Chart Studio Cloud for `bgcolor`.
    Sankey::Node::Hoverlabel& bgcolorsrc(std::string f);

    // Sets the border color of the hover labels for this trace.
    Sankey::Node::Hoverlabel& bordercolor(std::string f);
    Sankey::Node::Hoverlabel& bordercolor(double f);
    Sankey::Node::Hoverlabel& bordercolor(std::vector<std::string> f);
    Sankey::Node::Hoverlabel& bordercolor(std::vector<double> f);

    // Sets the source reference on Chart Studio Cloud for `bordercolor`.
    Sankey::Node::Hoverlabel& bordercolorsrc(std::string f);

    // Sets the font used in hover labels.
    Sankey::Node::Hoverlabel& font(Font f);

    // Sets the default length (in number of characters) of the trace name in the hover labels for all traces. -1 shows
    // the whole name regardless of length. 0-3 shows the first 0-3 characters, and an integer >3 will show the whole
    // name if it is less than that many characters, but if it is longer, will truncate to `namelength - 3` characters
    // and add an ellipsis.
    Sankey::Node::Hoverlabel& namelength(int f);
    Sankey::Node::Hoverlabel& namelength(std::vector<int> f);

    // Sets the source reference on Chart Studio Cloud for `namelength`.
    Sankey::Node::Hoverlabel& namelengthsrc(std::string f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

// Sets the font used in hover labels.
class Sankey::Node::Hoverlabel::Font {
 public:

    enum class Style {
        NORMAL,
        ITALIC,
    };
    static std::string to_string(Style e);

    enum class Textcase {
        NORMAL,
        WORD_CAPS,
        UPPER,
        LOWER,
    };
    static std::string to_string(Textcase e);

    enum class Variant {
        NORMAL,
        SMALL_CAPS,
        ALL_SMALL_CAPS,
        ALL_PETITE_CAPS,
        PETITE_CAPS,
        UNICASE,
    };
    static std::string to_string(Variant e);

    Sankey::Node::Hoverlabel::Font& color(std::string f);
    Sankey::Node::Hoverlabel::Font& color(double f);
    Sankey::Node::Hoverlabel::Font& color(std::vector<std::string> f);
    Sankey::Node::Hoverlabel::Font& color(std::vector<double> f);

    // Sets the source reference on Chart Studio Cloud for `color`.
    Sankey::Node::Hoverlabel::Font& colorsrc(std::string f);

    // HTML font family - the typeface that will be applied by the web browser. The web browser will only be able to
    // apply a font if it is available on the system which it operates. Provide multiple font families, separated by
    // commas, to indicate the preference in which to apply fonts if they aren't available on the system. The Chart
    // Studio Cloud (at https://chart-studio.plotly.com or on-premise) generates images on a server, where only a select
    // number of fonts are installed and supported. These include *Arial*, *Balto*, *Courier New*, *Droid Sans*, *Droid
    // Serif*, *Droid Sans Mono*, *Gravitas One*, *Old Standard TT*, *Open Sans*, *Overpass*, *PT Sans Narrow*,
    // *Raleway*, *Times New Roman*.
    Sankey::Node::Hoverlabel::Font& family(std::string f);
    Sankey::Node::Hoverlabel::Font& family(std::vector<std::string> f);

    // Sets the source reference on Chart Studio Cloud for `family`.
    Sankey::Node::Hoverlabel::Font& familysrc(std::string f);

    // Sets the kind of decoration line(s) with text, such as an *under*, *over* or *through* as well as combinations
    // e.g. *under+over*, etc.
    // - Default: none
    // - Flags: ['under', 'over', 'through']
    // - Extras ['none']
    Sankey::Node::Hoverlabel::Font& lineposition(std::string f);
    Sankey::Node::Hoverlabel::Font& lineposition(std::vector<std::string> f);

    // Sets the source reference on Chart Studio Cloud for `lineposition`.
    Sankey::Node::Hoverlabel::Font& linepositionsrc(std::string f);

    // Sets the shape and color of the shadow behind text. *auto* places minimal shadow and applies contrast text font
    // color. See https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow for additional options.
    Sankey::Node::Hoverlabel::Font& shadow(std::string f);
    Sankey::Node::Hoverlabel::Font& shadow(std::vector<std::string> f);

    // Sets the source reference on Chart Studio Cloud for `shadow`.
    Sankey::Node::Hoverlabel::Font& shadowsrc(std::string f);

    Sankey::Node::Hoverlabel::Font& size(double f);
    Sankey::Node::Hoverlabel::Font& size(std::vector<double> f);

    // Sets the source reference on Chart Studio Cloud for `size`.
    Sankey::Node::Hoverlabel::Font& sizesrc(std::string f);

    // Sets whether a font should be styled with a normal or italic face from its family.
    // - Default: normal
    Sankey::Node::Hoverlabel::Font& style(enum Style f);
    Sankey::Node::Hoverlabel::Font& style(const std::vector<enum Style>& f);

    // Sets the source reference on Chart Studio Cloud for `style`.
    Sankey::Node::Hoverlabel::Font& stylesrc(std::string f);

    // Sets capitalization of text. It can be used to make text appear in all-uppercase or all-lowercase, or with each
    // word capitalized.
    // - Default: normal
    Sankey::Node::Hoverlabel::Font& textcase(enum Textcase f);
    Sankey::Node::Hoverlabel::Font& textcase(const std::vector<enum Textcase>& f);

    // Sets the source reference on Chart Studio Cloud for `textcase`.
    Sankey::Node::Hoverlabel::Font& textcasesrc(std::string f);

    // Sets the variant of the font.
    // - Default: normal
    Sankey::Node::Hoverlabel::Font& variant(enum Variant f);
    Sankey::Node::Hoverlabel::Font& variant(const std::vector<enum Variant>& f);

    // Sets the source reference on Chart Studio Cloud for `variant`.
    Sankey::Node::Hoverlabel::Font& variantsrc(std::string f);

    // Sets the weight (or boldness) of the font.
    Sankey::Node::Hoverlabel::Font& weight(int f);
    Sankey::Node::Hoverlabel::Font& weight(std::vector<int> f);

    // Sets the source reference on Chart Studio Cloud for `weight`.
    Sankey::Node::Hoverlabel::Font& weightsrc(std::string f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

class Sankey::Node::Line {
 public:

    // Sets the color of the `line` around each `node`.
    Sankey::Node::Line& color(std::string f);
    Sankey::Node::Line& color(double f);
    Sankey::Node::Line& color(std::vector<std::string> f);
    Sankey::Node::Line& color(std::vector<double> f);

    // Sets the source reference on Chart Studio Cloud for `color`.
    Sankey::Node::Line& colorsrc(std::string f);

    // Sets the width (in px) of the `line` around each `node`.
    Sankey::Node::Line& width(double f);
    Sankey::Node::Line& width(std::vector<double> f);

    // Sets the source reference on Chart Studio Cloud for `width`.
    Sankey::Node::Line& widthsrc(std::string f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

class Sankey::Stream {
 public:

    // Sets the maximum number of points to keep on the plots from an incoming stream. If `maxpoints` is set to *50*,
    // only the newest 50 points will be displayed on the plot.
    Sankey::Stream& maxpoints(double f);

    // The stream id number links a data trace on a plot with a stream. See https://chart-studio.plotly.com/settings for
    // more details.
    Sankey::Stream& token(std::string f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

// Sets the font for node labels
class Sankey::Textfont {
 public:

    enum class Style {
        NORMAL,
        ITALIC,
    };
    static std::string to_string(Style e);

    enum class Textcase {
        NORMAL,
        WORD_CAPS,
        UPPER,
        LOWER,
    };
    static std::string to_string(Textcase e);

    enum class Variant {
        NORMAL,
        SMALL_CAPS,
        ALL_SMALL_CAPS,
        ALL_PETITE_CAPS,
        PETITE_CAPS,
        UNICASE,
    };
    static std::string to_string(Variant e);

    Sankey::Textfont& color(std::string f);
    Sankey::Textfont& color(double f);

    // HTML font family - the typeface that will be applied by the web browser. The web browser will only be able to
    // apply a font if it is available on the system which it operates. Provide multiple font families, separated by
    // commas, to indicate the preference in which to apply fonts if they aren't available on the system. The Chart
    // Studio Cloud (at https://chart-studio.plotly.com or on-premise) generates images on a server, where only a select
    // number of fonts are installed and supported. These include *Arial*, *Balto*, *Courier New*, *Droid Sans*, *Droid
    // Serif*, *Droid Sans Mono*, *Gravitas One*, *Old Standard TT*, *Open Sans*, *Overpass*, *PT Sans Narrow*,
    // *Raleway*, *Times New Roman*.
    Sankey::Textfont& family(std::string f);

    // Sets the kind of decoration line(s) with text, such as an *under*, *over* or *through* as well as combinations
    // e.g. *under+over*, etc.
    // - Default: none
    // - Flags: ['under', 'over', 'through']
    // - Extras ['none']
    Sankey::Textfont& lineposition(std::string f);

    // Sets the shape and color of the shadow behind text. *auto* places minimal shadow and applies contrast text font
    // color. See https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow for additional options.
    Sankey::Textfont& shadow(std::string f);

    Sankey::Textfont& size(double f);

    // Sets whether a font should be styled with a normal or italic face from its family.
    // - Default: normal
    Sankey::Textfont& style(enum Style f);

    // Sets capitalization of text. It can be used to make text appear in all-uppercase or all-lowercase, or with each
    // word capitalized.
    // - Default: normal
    Sankey::Textfont& textcase(enum Textcase f);

    // Sets the variant of the font.
    // - Default: normal
    Sankey::Textfont& variant(enum Variant f);

    // Sets the weight (or boldness) of the font.
    Sankey::Textfont& weight(int f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

} // namespace plotlypp

#include "impl/sankey_impl.hpp"
