name: CI Ubuntu GCC
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Enable manual trigger

jobs:
  call-build:
    strategy:
      fail-fast: false
      matrix:
        cpp_std: ["17", "23"]
    uses: ./.github/workflows/_build_template.yml
    with:
      os: ubuntu-latest
      compiler: gcc
      cxx: g++
      cc: gcc
      cpp_std: ${{ matrix.cpp_std }}
      # GCC 14 is needed for better modules support, but hit and ICE and segfaults due to running out of index space.
      # GCC 15 is not yet available for 24.04. (Note GCC 13 is the default installed.)
      build_modules: false


