name: CI Ubuntu Clang
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Enable manual trigger

jobs:
  call-build:
    strategy:
      fail-fast: false
      matrix:
        cpp_std: ["17", "23"]
    uses: ./.github/workflows/_build_template.yml
    with:
      os: ubuntu-latest
      compiler: clang
      cxx: clang++
      cc: clang
      cpp_std: ${{ matrix.cpp_std }}
      build_modules: ${{ matrix.cpp_std == '23' }}
      # The default clang package on Ubuntu does not include clang-scan-deps.
      install_cmd: |
        sudo apt-get update && sudo apt-get install -y --no-install-recommends clang-tools

