name: CI Windows MSVC
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Enable manual trigger

jobs:
  call-build:
    strategy:
      fail-fast: false
      matrix:
        cpp_std: ["17", "23"]
    uses: ./.github/workflows/_build_template.yml
    with:
      os: windows-latest
      compiler: msvc
      cxx: cl
      cc: cl
      cpp_std: ${{ matrix.cpp_std }}
      build_modules: ${{ matrix.cpp_std == '23' }}
